#-----------------------------------------------------#
#					LG UHC par uiytt				  #
#				Merci à Faywyrr pour son aide		  #
#					Version: 2.2.4					  #
#-----------------------------------------------------#
options:
	version: 2.2.4
	debug: false # true = permet aux ops d'avoir le même pouvoir que la Sorcière mais à volonté...

command /lg [<text="help">] [<text>] [<player>] [<text>]:
	trigger:
		if {lg::%player%::items} is not set:
			if arg 1 is set:
				if arg 1 is "setup":
					if player has permission "lgu.admin.setup" or "lgu.admin.*":
						if {lg::setup} is not set:
							set {lg::config::villager::size} to 1
							set {lg::config::hunter::size} to 0
							set {lg::config::witch::size} to 1
							set {lg::config::seer::size} to 0
							set {lg::config::girl::size} to 1
							set {lg::config::oldone::size} to 1
							set {lg::config::cupidon::size} to 1
							set {lg::config::fox::size} to 1
							set {lg::config::werewolf::size} to 1
							set {lg::config::Wwerewolf::size} to 1
							set {lg::config::Owerewolf::size} to 1
							set {lg::config::killer::size} to 1
							set {lg::config::wildchild::size} to 1
							set {lg::config::thief::size} to 1
							set {lg::config::Awerewolf::size} to 1
							set {lg::config::savior::size} to 1
							set {lg::config::inquisitor::size} to 1
							set {lg::config::angel::size} to 0
							set {lg::config::oracle::size} to 1
							set {lg::config::randomlover} to false

							set {lg::config::pvp} to 30 #temps en minutes avant que le pvp ne commence
							set {lg::config::day} to 40 #40 = 5m, 20 = 10m, 10 = 20m, 80 = 2m30, 160 = 1m15 ne pas choisir d'autres options....
							set {lg::config::day2} to "5-0" #proportionel à la ligne d'avant (40 = 5m = 5 minutes et 0 secondes soit "5-0")
							set {lg::config::dborder} to 2000 #taille totale de la bordure de départ (default : +1000/-1000 donc 2000)
							set {lg::config::fborder} to 500 #taille totale de la bordure finale (default : +250/-250 donc 500)
							set {lg::config::tborder} to 60 #temps en minutes avant que la border bouge
							set {lg::config::rtime} to 40 #temps en minutes avant que les rôles ne soit révélés
							set {lg::config::random} to true
							set {lg::config::deco} to "friends" #...
							set {lg::config::hide} to false

							set {lg::config::chat} to "region" #3 mode de communication : "region", "vocal" et "open"

							set {lg::config::optimining} to true
							set {lg::config::rod} to true
							set {lg::config::towers} to false
							set {lg::config::nether} to false
							set {lg::config::nofire} to false
							set {lg::config::diamondlimit} to false
							set {lg::config::diamondlimitsize} to 10
							set {lg::config::horse} to true
							set {lg::config::cutlean} to false
							set {lg::config::apple} to false
							set {lg::config::applerate} to 20
							set {lg::config::flint} to false
							set {lg::config::flintrate} to 50
							set {lg::config::nodeathbeforepvp} to false
							set {lg::config::finalheal} to false


							set {_world} to world of player
							make player execute command "/gamerule naturalRegeneration false"
							make player execute command "/gamerule reducedDebugInfo true"
							make player execute command "/gamerule showDeathMessages false"
							make player execute command "/gamerule sendCommandFeedback false"


							set {lg::setup} to true
							message "&8&l[&6&lLoup-garou&8&l] &7La partie a été correctement généré." to player
						else:
							message "&8&l[&6&lLoup-garou&8&l] &7La partie a déjà été généré." to player
					else:
						message "&8&l[&6&lLoup-garou&8&l] &cVous n'avez pas la permission nécessaire pour faire ça." to player
				else if arg 1 is "config":
					if player has permission "lgu.admin.config" or "lgu.admin.*":
						if {lg::info::start} is not true:
							if {lg::setup} is true:
								open virtual chest inventory with size 4 with name "&lConfigurer la partie" to player
								lgu_config(player,"Menu")
							else:
								message "&8&l[&6&lLoup-garou&8&l] &7Veuillez executer la commande /lg setup  au moins une fois" to player
						else:
							message "&8&l[&6&lLoup-garou&8&l] &7Vous ne pouvez pas faire cette commande durant une partie, faite /lg stop pour arréter cette partie." to player
					else:
						message "&8&l[&6&lLoup-garou&8&l] &cVous n'avez pas la permission nécessaire pour faire ça." to player
				else if arg 1 is "start":
					if player has permission "lgu.admin.start" or "lgu.admin.*":
						if {lg::setup} is true:
							if {lg::info::start} is false:
								delete {lg::info::start}
							if {lg::info::start} is not set:
								delete {lg::var::*}
								delete {lg::power::*}
								delete {lg::current::*}
								loop all players:
									delete {lg::%loop-player%::*}
								delete {lg::vote::*}
								delete {lg::joueurs::*}
								delete {lg::stuff::*}
								delete {lg::amoureux::*}
								delete {lg::killer::*}
								set {lg::info::start} to true
								make player execute command "/gamerule naturalRegeneration false"
								make player execute command "/gamerule reducedDebugInfo true"
								make player execute command "/gamerule showDeathMessages false"
								make player execute command "/gamerule sendCommandFeedback false"
								loop all players:
									apply resistance 4 without any particles to loop-player for 30 seconds
									set {lg::joueurs::%loop-player%} to loop-player
								loop {lg::spec::*}:
									if {lg::joueurs::%loop-value%} is set:
										delete {lg::joueurs::%loop-value%}
								if size of {lg::joueurs::*} is higher than 1:
									message "&8&l[&6&lLoup-garou&8&l] &7Téléportation en cours..." to all players
									lgu_scoreboard()
									set {lg::current::world} to world of player
									set time of world("%{lg::current::world}%") to 6:00
									loop {lg::joueurs::*}:
										milk loop-value
										set loop-value's max health to 10
										set loop-value's gamemode to survival
										clear loop-value's inventory
										heal loop-value
										set the loop-value's food level to 10
										set loop-value's xp to 0
										lgu_tp(loop-value,false)
										if {lg::items::*} is set:
											set {_s} to 0
											set {_p} to loop-value-1
											if {lg::items::items::*} is set:
												loop {lg::items::items::*}:
													set slot {_s} of {_p}'s inventory to loop-value-2
													add 1 to {_s}
											set {_p}'s helmet to {lg::items::helmet}
											set {_p}'s chestplate to {lg::items::chestplate}
											set {_p}'s leggings to {lg::items::leggings}
											set {_p}'s boots to {lg::items::boots}
										wait 1 second
									message "&8&l[&6&lLoup-garou&8&l] &7Téléportation terminé..." to all players
									message "&7-------------&bInfos&7-------------" to player
									message "&r- &bTaille bordure initiale: &7+%{lg::config::dborder} / 2%/-%{lg::config::dborder} / 2%" to all players
									message "&r- &bTaille bordure finale: &7+%{lg::config::fborder} / 2%/-%{lg::config::fborder} / 2%" to all players
									if {lg::config::deco} is "friends":
										message "&r- &bRègle pour la déconnexion : &7les joueurs peuvent se déco autant de temps qu'ils veulent sans mourrir." to all players
									else if {lg::config::deco} is "normal":
										message "&r- &bRègle pour la déconnexion : &7les joueurs ont 30 secondes pour se reconnecter avant de mourrir." to all players
									else:
										message "&r- &bRègle pour la déconnexion : &7les joueurs sont déclarés mort immédiatement." to all players
									if {lg::config::chat} is "region":
										message "&r- &bRègle pour le chat : &7les joueurs ne voient les messages des autres que si ils sont dans un rayon de 50 blocs autour d'eux." to all players
									else if {lg::config::chat} is "vocal":
										message "&r- &bRègle pour le chat : &7les joueurs ne peuvent pas parler dans le chat." to all players
									else:
										message "&r- &bRègle pour le chat : &7les joueurs peuvent parler dans le chat normalement." to all players
									if {lg::config::optimining} is true:
										message "&r- &bMinage optimisé : &aAutorisé" to all players
									else:
										message "&r- &bMinage optimisé : &cInterdit" to all players
									if {lg::config::towers} is true:
										message "&r- &bTower : &aAutorisé" to all players
									else:
										message "&r- &bTower : &cInterdit" to all players
									if {lg::config::nether} is true:
										message "&r- &bNether : &aActivé" to all players
									else:
										message "&r- &bNether : &cDésactivé" to all players
									if {lg::config::rod} is true:
										message "&r- &bFishing rod(canne à pêche) : &aAutorisé" to all players
									else:
										message "&r- &bFishing rod(canne à pêche) : &cInterdit" to all players
									if {lg::config::diamondlimit} is true:
										message "&r- &bLimite de diamants: &f%{lg::config::diamondlimitsize}%" to all players
									if {lg::config::horse} is true:
										message "&r- &bChevaux : &aAutorisé" to all players
									else:
										message "&r- &bChevaux : &cInterdit" to all players
									if {lg::config::nofire} is true:
										message "&r- &bNoFire : &aActivé" to all players
									if {lg::config::finalheal} is true:
										message "&r- &bFinal Heal : &aActivé"
									if {lg::config::nodeathbeforepvp} is true:
										message "&r- &bPas de mort avant le pvp : &aActivé"
									message "&c/!\ &7Merci de ne pas demander à un joueur de vous taper pour connaître son rôle ou de demander une lettre précise du rôle pour confirmer son rôle &c/!\" to all players
									lgu_roles()

									set center of world of player to location(0, 0, 0, world("%world of player%"))
									set diameter of world of player to {lg::config::dborder} over 1 second
									if {lg::config::day} is not equal to 20:
										while {lg::info::start} is equal to true:
											execute console command "/time add %{lg::config::day} - 20%"
											wait 1 second
								else:
									message "&8&l[&6&lLoup-garou&8&l] &cPas assez de joueurs pour commencer la partie..." to all players
									set {lg::info::start} to false
							else:
								message "&8&l[&6&lLoup-garou&8&l] &7La partie doit être arrétée afin d'en commencer une nouvelle." to player
						else:
							message "&8&l[&6&lLoup-garou&8&l] &7Vous devez faire /lg setup une fois avant de commencer une partie." to player
					else:
						message "&8&l[&6&lLoup-garou&8&l] &cVous n'avez pas la permission nécessaire pour faire ça." to player
				else if arg 1 is "stop":
					if player has permission "lgu.admin.stop" or "lgu.admin.*":
						if {lg::info::start} is true:
							set {lg::info::start} to false
							loop {lg::spec::*}:
								reset stylish scoreboard of loop-value
							delete {lg::spec::*}
							loop {lg::joueurs::*}:
								reset stylish scoreboard of loop-value
								delete {lg::%loop-value%::*}
								delete {lg::joueurs::%loop-value%}
								loop 10 times:
									skellett delete id based score "LG_UHC_%loop-number%" for stylish scoreboard with named "LG_UHC"
								skellett delete stylish scoreboard named "LG_UHC"

								reset world of player
							delete {lg::current::*}
							message "&8&l[&6&lLoup-garou&8&l] &7La partie a été arrêtée." to all players
						else:
							message "&8&l[&6&lLoup-garou&8&l] &7La partie n'est pas démarrée." to player
					else:
						message "&8&l[&6&lLoup-garou&8&l] &cVous n'avez pas la permission nécessaire pour faire ça." to player
				else if arg 1 is "spectator" or "spectateur" or "spec":
					if player has permission "lgu.admin.spec" or "lgu.admin.*":
						if {lg::info::start} is not true:
							if arg 2 is "add" or "remove":
								if arg 3 is set:
									if arg 2 is equal to "add":
										if {lg::spec::%arg 3%} is not set:
											set {lg::spec::%arg 3%} to arg 3
											message "&8&l[&6&lLoup-garou&8&l] &7Le joueur &3%arg 3% &7a été ajouté aux spectateurs..." to player
										else:
											message "&8&l[&6&lLoup-garou&8&l] &7Ce joueur est déjà spectateur..." to player
									else if arg 2 is equal to "remove":
										if {lg::spec::%arg 3%} is set:
											delete {lg::spec::%arg 3%}
											message "&8&l[&6&lLoup-garou&8&l] &7Le joueur &3%arg 3% &7a été enlevé de la liste des spectateurs..." to player
										else:
											message "&8&l[&6&lLoup-garou&8&l] &7Ce joueur n'est pas spectateur..." to player
								else:
									message "&8&l[&6&lLoup-garou&8&l] &7Syntaxe correcte: &c/lg spectateur (add|remove) <pseudo>" to player
							else:
								if arg 3 is not set:
									lgu_spec(player,1)
									message "&8&l[&6&lLoup-garou&8&l] &7Pour rajouter des spectateurs: &c/lg spectateur (add|remove) <pseudo>" to player
								else:
									message "&8&l[&6&lLoup-garou&8&l] &7Syntaxe correcte: &c/lg spectateur list" to player
						else:
							message "&8&l[&6&lLoup-garou&8&l] &7La partie est pas démarrée." to player
					else:
						message "&8&l[&6&lLoup-garou&8&l] &cVous n'avez pas la permission nécessaire pour faire ça." to player
				else if arg 1 is "force" or "skip":
					if player has permission "lgu.admin.force" or "lgu.admin.*":
						if {lg::info::start} is true:
							if arg 2 is equal to "mur" or "bordure":
								if {lg::current::border} is not true:
									lgu_eventmessage("border")
								else:
									message "&8&l[&6&lLoup-garou&8&l] &cLe mur a déjà bougé" to player
							else if arg 2 is equal to "pvp" or "combat":
								if {lg::current::pvp} is not true:
									lgu_eventmessage("pvp")
								else:
									message "&8&l[&6&lLoup-garou&8&l] &cLe mur pvp est déjà activé" to player
							else if arg 2 is equal to "revelation" or "rev" or "roles" or "role" or "rôle" or "rôles":
								if {lg::current::rev} is not true:
									lgu_eventmessage("roles")
								else:
									message "&8&l[&6&lLoup-garou&8&l] &cLes rôles on déjà été donné" to player
							else:
								message "&8&l[&6&lLoup-garou&8&l] &7Syntaxe correcte: &c/lg force (pvp|bordure|revelation)" to player
						else:
							message "&8&l[&6&lLoup-garou&8&l] &7La partie n'est pas démarrée." to player
					else:
						message "&8&l[&6&lLoup-garou&8&l] &cVous n'avez pas la permission nécessaire pour faire ça." to player
				else if arg 1 is "roles" or "description":
					if {lg::info::start} is equal to true:
						if {lg::config::hide} is false:
							loop {lg::joueurs::*}:
								add {lg::%loop-value%::role} to {_role::*}
							message "&8&l>> &aRôles encore présents dans la partie :"
							loop (size of {_role::*}) times:
								set {_r} to random object out of {_role::*}
								remove {_r} from {_role::*}
								message "<tooltip:&8Cliquez pour voir la description du rôle.><cmd:/lg role %{_r}%>&7- %{_r}%" to player
						else:
							message "&8&l[&6&lLoup-garou&8&l] &7La composition des rôles est cachée." to player
					else:
						message "&8&l[&6&lLoup-garou&8&l] &7La partie n'est pas lancée." to player
				else if arg 1 is "reset":
					if player has permission "lgu.admin.reset" or "lgu.admin.*":

						delete {lg::config::*}
						delete {lg::var::*}
						delete {lg::power::*}
						delete {lg::current::*}
						loop {lg::joueurs::*}:
							delete {lg::%loop-value%::*}
						delete {lg::vote::*}
						delete {lg::joueurs::*}
						delete {lg::stuff::*}
						delete {lg::amoureux::*}
						delete {lg::killer::*}
						delete {lg::*}
						loop all players:
							reset stylish scoreboard of loop-player
						delete stylish scoreboard named "LG_UHC"
						reset world of player
						message "&8&l[&6&lLoup-garou&8&l] &7L'ensemble des variables ont été supprimées." to all players
						message "&8&l[&6&lLoup-garou&8&l] &7Si vous avez eu un bug, merci de le signaler sur discord à uiytt##7002." to all players
				else if arg 1 is "power":
					if {lg::current::rev} is true:
						if {lg::power::%player%} is not set:
							if {lg::%player%::role} is "Sorcière":
								if arg 2 is "Sorcière":
									if arg 3 is online:
										if {lg::var::%arg 3%} is set:
											set {lg::power::%player%} to true
											delete {lg::var::%arg 3%}
											message "&8&l[&aVous avez ressucité le joueur &3%arg 3%&8&l]" to player
											set gamemode of arg 3 to survival
											remove blindness from arg 3
											lgu_tp(arg 3,true)
											set offhand tool of arg 3 to totem of undying
											damage arg 3 by 40

											give {lg::stuff::%arg 3%::*} to arg 3
										else:
											message "&cLe joueur &3%arg 3% &cne peut plus être réssucité" to player
									else:
										message "&cLe joueur &3%arg 3% &cn'est plus connecté" to player
								else:
									message "&cVous n'avez pas le rôle nécessaire" to player
							else if {lg::%player%::role} is "Infect père des loups":
								if arg 2 is "lg":
									if arg 3 is online:
										if {lg::killer::%arg 3%} is true:
											if {lg::var::%arg 3%} is set:
												set {lg::power::%player%} to true
												delete {lg::killer::%arg 3%}
												delete {lg::var::%arg 3%}
												message "&8&l[&aVous avez transformé le joueur &3%arg 3% &aen &cloup-garou&8&l]" to player
												set gamemode of arg 3 to survival
												remove blindness from arg 3
												lgu_tp(arg 3,true)
												give {lg::stuff::%arg 3%::*} to arg 3
												set {lg::%arg 3%::role} to "Loup-garou"
												message "&8&l>> &2&lTu es devenu Loup-garou" to arg 3
												message "&7Tu es désormais un ennemi du village." to arg 3
												message "&fTu peux parler aux autres loups-garous durant la nuit en mettant un ""*"" devant ton message." to arg 3
												message "&fTu peux voir la liste des autres loups-garous en faisant /lg lg" to arg 3
												message "" to arg 3
												message "&6Tu peux gagner ..." to arg 3
												message "&8&l>> &fsi les villageois, le loup-garou blanc et l'assassin sont morts." to arg 3
												message "" to arg 3
												message "&3Pour faire ceci, tu as le droit à :" to arg 3
												message "&a&l+ &r&7un effet de force nocturne" to arg 3
												message "&a&l+ &r&7un effet de vision nocturne" to  arg 3
												loop {lg::joueurs::*}:
													if {lg::%loop-value%::role} is "Loup-garou" or "Infect père des loups" or "Loup-garou blanc":
														message "&8&l[&c&lLG&8&l] &7Le joueur &3%arg 3% &7est devenu &cloup-garou&7." to loop-value
														add loop-value to {_lg::*}
												set {_lg} to "%{_lg::*}%"
												replace all "and" in {_lg} with "et"
												message "&8&l[&cLOUP-GAROU&8&l] &c%{_lg}%" to arg 3
												set {_osef} to lgu_wincheck()
											else:
												message "&cLe joueur &3%arg 3% &cne peut plus être réssucité" to player
									else:
										message "&cLe joueur &3%arg 3% &cn'est plus connecté" to player
								else:
									message "&cVous n'avez pas le rôle nécessaire" to player
							else if {lg::%player%::role} is "Cupidon":
								if {lg::amoureux::1} is not set:
									if arg 2 is "Cupidon":
										lgu_cupidon(player,1,false)
									else:
										message "&cVous n'avez pas le rôle nécessaire" to player
							else if {lg::%player%::role} is "Inquisiteur":
								if {lg::%player%::power} is not set:
									if arg 2 is "Inquisiteur":
										lgu_inquisitor(player,1)
									else:
										message "&cVous n'avez pas le rôle nécessaire" to player
							else if {lg::%player%::role} is "Chasseur":
								if {lg::%player%::power} is not set:
									if arg 2 is "Chasseur":
										lgu_hunter(player,1)
									else:
										message "&cVous n'avez pas le rôle nécessaire" to player
							else if {lg::%player%::role} is "Voyante":
								if arg 2 is "Voyante":
									if {lg::power::%player%} is not set:
										if {lg::current::vote} is true:
											lgu_voyante(player,1)
								else:
									message "&cVous n'avez pas le rôle nécessaire" to player
							else if {lg::%player%::role} is "Oracle":
								if arg 2 is "Oracle":
									if {lg::power::%player%} is not set:
										if {lg::current::vote} is true:
											lgu_oracle(player,1,"<none>")
								else:
									message "&cVous n'avez pas le rôle nécessaire" to player
							else if {lg::%player%::role} is "Salvateur":
								if arg 2 is "Salvateur":
									if {lg::power::%player%} is not set:
										if {lg::current::vote} is true:
											lgu_salvateur(player,1)
								else:
									message "&cVous n'avez pas le rôle nécessaire" to player
							else if {lg::%player%::role} is "Enfant sauvage":
								if {lg::power::%player%} is not set:
									if arg 2 is "wildchild":
										lgu_wildchild(player,1)
									else:
										message "&cVous ne pouvez pas faire cette commande" to player

					if arg 2 is "op":
						if player has permission "lgu.admin.respawn" or "lgu.admin.*" or "lgu.*":
							if {@debug} is true:
								if {lg::var::%arg 3%} is set:
									delete {lg::var::%arg 3%}
									message "&8&l[&aVous avez sauvé le joueur &3%arg 3%&8&l]" to player
									set gamemode of arg 3 to survival
									remove blindness from arg 3
									lgu_tp(arg 3,true)
									give {lg::stuff::%arg 3%::*} to arg 3
				else if arg 1 is "respawn":
					if player has permission "lgu.admin.respawn" or "lgu.admin.*":
						if {lg::info::start} is true:
							if arg 2 is set:
								set {_player} to arg 2 parsed as player
								if {_player} is online:
									if {lg::joueurs::%{_player}%} is not set:
										lgu_respawn(player,{_player})
									else:
										message "&8&l[&6&lLoup-garou&8&l] &7Ce joueur est vivant, il ne peut pas être réssucité."
								else:
									message "&8&l[&6&lLoup-garou&8&l] &7Ce joueur n'est pas connecté, il ne peut pas être réssucité."
							else:
								message "&8&l[&6&lLoup-garou&8&l] &7Syntaxe correcte: &c/lg respawn <pseudo>"
						else:
							message "&8&l[&6&lLoup-garou&8&l] &7La partie doit être lancée pour faire cette commande" to player
					else:
						message "&8&l[&6&lLoup-garou&8&l] &cVous n'avez pas la permission nécessaire pour faire ça." to player
				else if arg 1 is "y":
					if {lg::info::start} is equal to true:
						message "&7Y: &a%round(y-location of player)%" to player
					else:
						message "&8&l[&6&lLoup-garou&8&l] &7La partie doit être lancée pour faire cette commande" to player
				else if arg 1 is "vote":
					if {lg::info::start} is equal to true:
						if {lg::current::vote} is true:
							if player's gamemode is survival or creative:
								lgu_vote(player,1)
					else:
						message "&8&l[&6&lLoup-garou&8&l] &7La partie doit être lancée pour faire cette commande" to player
				else if arg 1 is "flairer":
					if {lg::info::start} is equal to true:
						if {lg::current::rev} is true:
							if {lg::%player%::role} is "Renard":
								if {lg::power::%player%} is not set:
									set {lg::power::%player%} to 0
								if {lg::power::%player%} is smaller than 3:
									if arg 2 or arg 3 is not set:
										loop all players in radius 50 of location of player:
											if loop-value is not player:
												if {lg::%loop-value%::role} is "Loup-garou" or "Infect père des loups" or "Loup-garou blanc":
													message "&8&l[&6Tu as flairé un loup-garou&8&l]" to player
													add 1 to {lg::power::%player%}
													stop
										message "&8&l[&6Tu n'as rien flairé&8&l]" to player
										add 1 to {lg::power::%player%}
									else:
										message "&8&l[&6&lLoup-garou&8&l] &7Syntaxe correcte : &c/lg flairer &7pour vérifier la présence d'un lg dans les 50 blocs." to player
								else:
									message "&8&l[&6&lLoup-garou&8&l] &7Tu ne peux faire cette commande que 3 fois." to player
							else:
								message "&8&l[&6&lLoup-garou&8&l] &7Tu n'est pas le renard." to player
						else:
							message "&8&l[&6&lLoup-garou&8&l] &7Tu ne connais pas ton rôle." to player
					else:
						message "&8&l[&6&lLoup-garou&8&l] &7La partie doit être lancée pour faire cette commande" to player
				else if arg 1 is "lg":
					if {lg::info::start} is equal to true:
						if {lg::current::rev} is true:
							if {lg::%player%::role} is "Loup-garou" or "Loup-garou blanc" or "Infect père des loups":
								loop {lg::joueurs::*}:
									if {lg::%loop-value%::role} is "Loup-garou" or "Loup-garou blanc" or "Infect père des loups":
										add loop-value to {_lg::*}
								set {_lg} to "%{_lg::*}%"
								replace all "and" in {_lg} with "et"
								message "&8&l[&cLOUP-GAROU&8&l] &c%{_lg}%" to player
						else:
							message "&8&l[&6&lLoup-garou&8&l] &7Les rôles n'ont pas encore été dévoilés." to player
					else:
						message "&8&l[&6&lLoup-garou&8&l] &7La partie doit être lancée pour faire cette commande" to player
				else if arg 1 is "role" or "p":
					if {lg::info::start} is equal to true:
						if arg 2 is not set:
							if {lg::current::rev} is true:
								if {lg::%player%::role} is set:
									lgu_rolesgive(player,{lg::%player%::role},false)
								else:
									message "&8&l[&6&lLoup-garou&8&l] &7Tu es spectateur" to player
							else:
								if {lg::%player%::role} is set:
									message "&8&l[&6&lLoup-garou&8&l] &7Tu es &e?????&7." to player
								else:
									message "&8&l[&6&lLoup-garou&8&l] &7Tu es spectateur" to player
						else:
							lgu_rolesgive(player,arg 2,false)
					else:
						message "&8&l[&6&lLoup-garou&8&l] &7La partie doit être lancée pour faire cette commande" to player
				else if arg 1 is "info" or "infos" or "game" or "gameinfo":
					message "&7-------------&bInfos&7-------------" to player
					message "&r- &bTaille bordure initiale: &7+%{lg::config::dborder} / 2%/-%{lg::config::dborder} / 2%" to player
					message "&r- &bTaille bordure finale: &7+%{lg::config::fborder} / 2%/-%{lg::config::fborder} / 2%" to player
					if {lg::config::deco} is "friends":
						message "&r- &bRègle pour la déconnexion : &7les joueurs peuvent se déco autant de temps qu'ils veulent sans mourrir." to player
					else if {lg::config::deco} is "normal":
						message "&r- &bRègle pour la déconnexion : &7les joueurs ont 30 secondes pour se reconnecter avant de mourrir." to player
					else:
						message "&r- &bRègle pour la déconnexion : &7les joueurs sont déclarés mort immédiatement." to player
					if {lg::config::chat} is "region":
						message "&r- &bRègle pour le chat : &7les joueurs ne voient les messages des autres que si ils sont dans un rayon de 50 blocs autour d'eux." to player
					else if {lg::config::chat} is "vocal":
						message "&r- &bRègle pour le chat : &7les joueurs ne peuvent pas parler dans le chat." to player
					else:
						message "&r- &bRègle pour le chat : &7les joueurs peuvent parler dans le chat normalement." to player
					if {lg::config::optimining} is true:
						message "&r- &bMinage optimisé : &aAutorisé" to player
					else:
						message "&r- &bMinage optimisé : &cInterdit" to player
					if {lg::config::towers} is true:
						message "&r- &bTower : &aAutorisé" to player
					else:
						message "&r- &bTower : &cInterdit" to player
					if {lg::config::nether} is true:
						message "&r- &bMinage optimisé : &aActivé" to player
					else:
						message "&r- &bMinage optimisé : &cDésactivé" to player
					if {lg::config::rod} is true:
						message "&r- &bFishing rod (canne à pêche) : &aAutorisé" to player
					else:
						message "&r- &bFishing rod (canne à pêche) : &cInterdit" to player
					if {lg::config::diamondlimit} is true:
						message "&r- &bLimite de diamants: &f%{lg::config::diamondlimitsize}%" to player
					if {lg::config::horse} is true:
						message "&r- &bChevaux : &aAutorisé" to player
					else:
						message "&r- &bChevaux : &cInterdit" to player
					if {lg::config::nofire} is true:
						message "&r- &bNoFire : &aActivé" to player
					if {lg::config::finalheal} is true:
						message "&r- &bFinal Heal : &aActivé"
					if {lg::config::nodeathbeforepvp} is true:
						message "&r- &bPas de mort avant le pvp : &aActivé"
					message "&c/!\ &7Merci de ne pas demander à un joueur de vous taper pour connaître son rôle ou de demander une lettre précise du message rôle pour confirmer son rôle &c/!\" to player
				else if arg 1 is "help":
					message "&8&l[&6&lLoup-garou&8&l] &7/&elg &b..." to player
					message "&r &b roles &7- &rVoir les rôles encore vivants" to player
					message "&r &b vote &7- &rVoter lors du début du jour" to player
					message "&r &b info &7- &rvoir toutes les infos de la partie." to player
					message "&r &b help &7- &rVoir cette page" to player
					if player has permission "lgu.admin.setup" or "lgu.admin.*":
						message "&r &b setup &7- &rCommande à faire lors de l'installation du LG UHC" to player
					if player has permission "lgu.admin.config" or "lgu.admin.*":
						message "&r &b config &7- &rConfigurer la partie" to player
					if player has permission "lgu.admin.start" or "lgu.admin.*":
						message "&r &b start &7- &rDémarrer une partie" to player
					if player has permission "lgu.admin.stop" or "lgu.admin.*":
						message "&r &b stop &7- &rArréter une partie" to player
					if player has permission "lgu.admin.spec" or "lgu.admin.*":
						message "&r &b spec &7- &rGérer les spéctateurs" to player
					if player has permission "lgu.admin.force" or "lgu.admin.*":
						message "&r &b force (mur|pvp|revelation)&7- &rLancer un évènement durant une partie" to player
					if player has permission "lgu.admin.respawn" or "lgu.admin.*":
						message "&r &b respawn <pseudo>&7- &rFaire rentrer un joueur dans une partie en cours." to player
					if player has permission "lgu.admin.version" or "lgu.admin.*":
						message "&r &b version &7- &rVoir la version du script" to player
					if player has permission "lgu.admin.reset" or "lgu.admin.*":
						message "&r &c reset &7- &rSupprimer TOUTES les variables (seulement dans le cas où vous désinstallez Lg UHC)." to player
					message "&r &b y &7- &rIndique votre cordonné y." to player
					message "&r &b lg &7- &rPermet aux loups-garous de voir les autres loups-garous" to player
					message "&r &b flairer &7- &rPermet au Renard de vérifier si il y a un loup-garou dans un rayon de 50 blocs" to player
					message "&r &b role &7ou &bp &7- &rVoir son rôle." to player
					message "&r  &eLes lg peuvent se parler entre eux en mettant ""*"" devant leurs messages. Les amoureux peuvent faire de même avec ""!"""
				else if arg 1 is "version" or "v":
					message "&8&l[&6&lLoup-garou&8&l] &7Version : &e{@version} &7par : &euiytt" to player
					message "&8&l[&6&lLoup-garou&8&l] &7Discord : &euiytt##7002" to player
				else:
					message "&8&l[&6&lLoup-garou&8&l] &7/&elg &b..." to player
					message "&r &b roles &7- &rVoir les rôles encore vivants" to player
					message "&r &b vote &7- &rVoter lors du début du jour" to player
					message "&r &b info &7- &rvoir toutes les infos de la partie." to player
					message "&r &b help &7- &rVoir cette page" to player
					if player has permission "lgu.admin.setup" or "lgu.admin.*":
						message "&r &b setup &7- &rCommande à faire lors de l'installation du LG UHC" to player
					if player has permission "lgu.admin.config" or "lgu.admin.*":
						message "&r &b config &7- &rConfigurer la partie" to player
					if player has permission "lgu.admin.start" or "lgu.admin.*":
						message "&r &b start &7- &rDémarrer une partie" to player
					if player has permission "lgu.admin.stop" or "lgu.admin.*":
						message "&r &b stop &7- &rArréter une partie" to player
					if player has permission "lgu.admin.spec" or "lgu.admin.*":
						message "&r &b spec &7- &rGérer les spéctateurs" to player
					if player has permission "lgu.admin.force" or "lgu.admin.*":
						message "&r &b force (mur|pvp|revelation)&7- &rLancer un évènement durant une partie" to player
					if player has permission "lgu.admin.respawn" or "lgu.admin.*":
						message "&r &b respawn <pseudo>&7- &rFaire rentrer un joueur dans une partie en cours." to player
					if player has permission "lgu.admin.version" or "lgu.admin.*":
						message "&r &b version &7- &rVoir la version du script" to player
					if player has permission "lgu.admin.reset" or "lgu.admin.*":
						message "&r &c reset &7- &rSupprimer TOUTES les variables (seulement dans le cas où vous désinstallez Lg UHC)." to player
					message "&r &b y &7- &rIndique votre cordonné y." to player
					message "&r &b lg &7- &rPermet aux loups-garous de voir les autres loups-garous" to player
					message "&r &b flairer &7- &rPermet au Renard de vérifier si il y a un loup-garou dans un rayon de 50 blocs" to player
					message "&r &b role &7ou &bp &7- &rVoir son rôle." to player
					message "&r  &eLes lg peuvent se parler entre eux en mettant ""*"" devant leurs messages. Les amoureux peuvent faire de même avec ""!"""
		else:
			if arg 1 is "finish":
				if {lg::%player%::items} is "items":
					delete {lg::items::*}
					loop 36 times:
						add slot (loop-number - 1) of player's inventory to {lg::items::items::*}
					set {lg::items::helmet} to player's helmet
					set {lg::items::chestplate} to player's chestplate
					set {lg::items::leggings} to player's leggings
					set {lg::items::boots} to player's boots
					clear player's inventory
					delete {lg::%player%::items}
					message "&8&l[&6&lLoup-garou&8&l] &7Vous avez correctement défini les items de départ" to player
					lgu_config(player,"items")
				else:
					delete {lg::deathitems::*}
					loop 36 times:
						add slot (loop-number - 1) of player's inventory to {lg::deathitems::items::*}
					clear player's inventory
					delete {lg::%player%::items}
					message "&8&l[&6&lLoup-garou&8&l] &7Vous avez correctement défins les items de mort" to player
					lgu_config(player,"death")
			else:
				message "&8&l[&6&lLoup-garou&8&l] &7Faites /lg finish pour finir la configuration des items de départ" to player


function lgu_config(p: player,t: text):
	unformat all gui slots of {_p}

	if {_t} is "Menu":
		open virtual chest inventory with size 4 with name "&lConfigurer la partie" to {_p}
		make a gui slot 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 28, 29, 30, 31, 32, 33, 34 and 35 of {_p} with 1 gray stained glass pane named "&f"
		make a gui slot 10 of {_p} with 1 item frame named "&eDéfinir les rôles" with lore "&7Cliquez pour personaliser" and "&7les rôles" and "" and "&a>> &lCliquez pour changer" to run:
			lgu_config({_p},"roles")
		if {lg::config::pvp} is equal to 0:
			make a gui slot 11 of {_p} with 1 diamond sword named "&eDébut du pvp" with lore "&7Le pvp commencera " and "&7au &6début de la partie " and "" and "&a>> &lCliquez pour changer" to run:
				lgu_config({_p},"pvp")
		else if {lg::config::pvp} is higher than 0:
			make a gui slot 11 of {_p} with 1 diamond sword named "&eDébut du pvp" with lore "&7Le pvp commencera " and "&7au bout de &6%{lg::config::pvp}% &7minutes" and "" and "&a>> &lCliquez pour changer" to run:
				lgu_config({_p},"pvp")
		if {lg::config::day} is equal to 40:
			make a gui slot 12 of {_p} with 1 glowstone block named "&eDurée d'un jour / nuit" with lore "&7>> &lEtendue&7: 20 minutes " and "&7>> &lMinecraft&7: 10 minutes " and "&6>> &lLg UHC normal&7: 5 minutes " and "&7>> &lRapide&7: 2m30 " and "&7>> &lExtrème&7: 1m15 " and "" and "&a>> &lCliquez pour changer " to run:
				set {lg::config::day} to 80
				set {lg::config::day2} to "2-30"
				lgu_config({_p},"Menu")
		else if {lg::config::day} is equal to 80:
			make a gui slot 12 of {_p} with 1 glowstone block named "&eDurée d'un jour / nuit" with lore "&7>> &lEtendue&7: 20 minutes " and "&7>> &lMinecraft&7: 10 minutes " and "&7>> &lLg UHC normal&7: 5 minutes " and "&6>> &lRapide&7: 2m30 " and "&7>> &lExtrème&7: 1m15 " and "" and "&a>> &lCliquez pour changer " to run:
				set {lg::config::day} to 160
				set {lg::config::day2} to "1-15"
				lgu_config({_p},"Menu")
		else if {lg::config::day} is equal to 160:
			make a gui slot 12 of {_p} with 1 glowstone block named "&eDurée d'un jour / nuit" with lore "&7>> &lEtendue&7: 20 minutes " and "&7>> &lMinecraft&7: 10 minutes " and "&7>> &lLg UHC normal&7: 5 minutes " and "&7>> &lRapide&7: 2m30 " and "&6>> &lExtrème&7: 1m15 " and "" and "&a>> &lCliquez pour changer " to run:
				set {lg::config::day} to 10
				set {lg::config::day2} to "20-0"
				lgu_config({_p},"Menu")
		else if {lg::config::day} is equal to 10:
			make a gui slot 12 of {_p} with 1 glowstone block named "&eDurée d'un jour / nuit" with lore "&6>> &lEtendue&7: 20 minutes " and "&7>> &lMinecraft&7: 10 minutes " and "&7>> &lLg UHC normal&7: 5 minutes " and "&7>> &lRapide&7: 2m30 " and "&7>> &lExtrème&7: 1m15 " and "" and "&a>> &lCliquez pour changer " to run:
				set {lg::config::day} to 20
				set {lg::config::day2} to "10-0"
				lgu_config({_p},"Menu")
		else if {lg::config::day} is equal to 20:
			make a gui slot 12 of {_p} with 1 glowstone block named "&eDurée d'un jour / nuit" with lore "&7>> &lEtendue&7: 20 minutes " and "&6>> &lMinecraft&7: 10 minutes " and "&7>> &lLg UHC normal&7: 5 minutes " and "&7>> &lRapide&7: 2m30 " and "&7>> &lExtrème&7: 1m15 " and "" and "&a>> &lCliquez pour changer " to run:
				set {lg::config::day} to 40
				set {lg::config::day2} to "5-0"
				lgu_config({_p},"Menu")
		make a gui slot 13 of {_p} with 1 light blue glass block named "&eBordure de départ" with lore "&7La bordure de &adépart &7est " and "&7défintit à &6+%{lg::config::dborder} / 2%/-%{lg::config::dborder} / 2% " and "" and "&a>> &lCliquez pour changer " to run:
			lgu_config({_p},"dborder")
		make a gui slot 14 of {_p} with 1 red glass block named "&eBordure finale" with lore "&7La bordure &cfinale &7est " and "&7défintit à &6+%{lg::config::fborder} / 2%/-%{lg::config::fborder} / 2% " and "" and "&a>> &lCliquez pour changer " to run:
			lgu_config({_p},"fborder")
		make a gui slot 15 of {_p} with 1 barrier named "&eTemps avant que la bordure ne bouge" with lore "&7La bordure commencera " and "&7à bouger au bout de " and "&6%{lg::config::tborder}% &7minutes " and "" and "&a>> &lCliquez pour changer " to run:
			lgu_config({_p},"tborder")
		make a gui slot 16 of {_p} with 1 chest named "&eItems de départ" with lore "&7Les items qui sont donnés au " and "&7début de la partie aux joueurs " and "" and "&a>> &lCliquez pour changer" to run:
			lgu_config({_p},"items")
		if {lg::config::chat} is equal to "region":
			make a gui slot 20 of {_p} with 1 paper named "&eParamètre du chat" with lore "&7>> &lMode vocale: &7chat désactivé " and "&7>> &lMode chat ouvert: &7chat " and "&7normal sans limite " and "&6>> &lMode région: &7chat dans " and "&7une région de 50 blocs " and "" and "&a>> &lCliquez pour changer " to run:
				set {lg::config::chat} to "vocal"
				lgu_config({_p},"Menu")
		else if {lg::config::chat} is equal to "vocal":
			make a gui slot 20 of {_p} with 1 paper named "&eParamètre du chat" with lore "&6>> &lMode vocale: &7chat désactivé " and "&7>> &lMode chat ouvert: &7chat " and "&7normal sans limite " and "&7>> &lMode région: &7chat dans " and "&7une région de 50 blocs " and "" and "&a>> &lCliquez pour changer " to run:
				set {lg::config::chat} to "open"
				lgu_config({_p},"Menu")
		else:
			make a gui slot 20 of {_p} with 1 paper named "&eParamètre du chat" with lore "&7>> &lMode vocale: &7chat désactivé " and "&6>> &lMode chat ouvert: &7chat " and "&7normal sans limite " and "&7>> &lMode région: &7chat dans " and "&7une région de 50 blocs " and "" and "&a>> &lCliquez pour changer " to run:
				set {lg::config::chat} to "region"
				lgu_config({_p},"Menu")
		if {lg::config::rtime} is not equal to 0:
			make a gui slot 19 of {_p} with 1 book named "&eRévélation des rôles" with lore "&7Les rôles sont révélés " and "&7au bout de &6%{lg::config::rtime}% &7minutes " and "" and "&a>> &lCliquez pour changer " to run:
				lgu_config({_p},"rtime")
		else:
			make a gui slot 19 of {_p} with 1 book named "&eRévélation des rôles" with lore "&7Les rôles sont révélés " and "&7au &6début de la partie " and "" and "&a>> &lCliquez pour changer " to run:
				lgu_config({_p},"rtime")
		if {lg::config::deco} is equal to "close":
			make a gui slot 21 of {_p} with 1 beacon named "&eParamètre de déco/reco" with lore "&6>> &lMode fermé: &7Les joueurs se font " and "&7immédiatement kick de la partie à " and "&7leurs déconnexion " and "&7>> &lMode normal: &7Les joueurs " and "&7se font kick 30s après leurs " and "&7déconnexions " and "&7>> &lMode amis: &7les joueurs " and "&7ne se font pas kick lors de " and "&7leurs déconnexions " and "" and "&a>> &lCliquez pour changer " to run:
				set {lg::config::deco} to "normal"
				lgu_config({_p},"Menu")
		else if {lg::config::deco} is equal to "normal":
			make a gui slot 21 of {_p} with 1 beacon named "&eParamètre de déco/reco" with lore "&7>> &lMode fermé: &7Les joueurs se font " and "&7immédiatement kick de la partie à " and "&7leurs déconnexion " and "&6>> &lMode normal: &7Les joueurs " and "&7se font kick 30s après leurs " and "&7déconnexions " and "&7>> &lMode amis: &7les joueurs " and "&7ne se font pas kick lors de " and "&7leurs déconnexions " and "" and "&a>> &lCliquez pour changer " to run:
				set {lg::config::deco} to "friends"
				lgu_config({_p},"Menu")
		else:
			make a gui slot 21 of {_p} with 1 beacon named "&eParamètre de déco/reco" with lore "&7>> &lMode fermé: &7Les joueurs se font " and "&7immédiatement kick de la partie à " and "&7leurs déconnexion " and "&7>> &lMode normal: &7Les joueurs " and "&7se font kick 30s après leurs " and "&7déconnexions " and "&6>> &lMode amis: &7les joueurs " and "&7ne se font pas kick lors de " and "&7leurs déconnexions " and "" and "&a>> &lCliquez pour changer " to run:
				set {lg::config::deco} to "close"
				lgu_config({_p},"Menu")
		make a gui slot 22 of {_p} with 1 ender chest named "&eItems de mort" with lore "&7Les items qui sont droppés à " and "&7la mort d'un joueur " and "" and "&a>> &lCliquez pour changer" to run:
			lgu_config({_p},"death")
		make a gui slot 23 of {_p} with 1 string named "&eRègles" with lore "" and "" and "&a>> &lCliquez pour changer" to run:
			lgu_config({_p},"rules")
		make a gui slot 24 of {_p} with 1 empty ender portal frame named "&eScénarios" with lore "" and "" and "&a>> &lCliquez pour changer" to run:
			lgu_config({_p},"scenar")
	else if {_t} is "roles":
		open virtual chest inventory with size 5 with name "&lConfigurer les rôles" to {_p}
		make a gui slot 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 41, 42 and 43 of {_p} with 1 gray stained glass pane named "&f"
		make a gui slot 40 of {_p} with 1 arrow named "&eExtras (Déconseillé)" to run:
			lgu_config({_p},"extras")
		if {lg::config::random} is false:

			make a gui slot 44 of {_p} with 1 compass named "&eMode aléatoire" with lore "&7Les rôles activés seront distribués " and "&7peut importe le nombre de joueurs." to run:
				set {lg::config::random} to true
				lgu_config({_p},"roles")
			make a gui slot 0 of {_p} with a map named "&7&lRevenir en arrière -->" to run:
				lgu_config({_p},"Menu")
			set {_s} to 10
			loop 16 times:
				if {_s} is 17:
					set {_s} to 19
				if {_s} is 26:
					set {_s} to 28
				if {_s} is 10:
					set {_item} to "1 chest"
					set {_displayname} to "Nbr de villageois"
					set {_name} to "villager"
				else if {_s} is 11:
					set {_item} to "1 flint and steel"
					set {_displayname} to "Nbr d'Inquisiteurs'"
					set {_name} to "inquisitor"
				else if {_s} is 12:
					set {_item} to "1 potion of healing"
					set {_displayname} to "Nbr de sorcieres"
					set {_name} to "witch"
				else if {_s} is 13:
					set {_item} to "1 magma cream"
					set {_displayname} to "Nbr d'oracles"
					set {_name} to "oracle"
				else if {_s} is 14:
					set {_item} to "1 eye of ender"
					set {_displayname} to "Nbr de petite filles"
					set {_name} to "girl"
				else if {_s} is 15:
					set {_item} to "1 oak sapling"
					set {_displayname} to "Nbr d'anciens"
					set {_name} to "oldone"
				else if {_s} is 19:
					set {_item} to "1 name tag"
					set {_displayname} to "Nbr de renards"
					set {_name} to "fox"
				else if {_s} is 20:
					set {_item} to "1 rotten flesh"
					set {_displayname} to "Nbr de loups garous"
					set {_name} to "werewolf"
				else if {_s} is 21:
					set {_item} to "1 white dye"
					set {_displayname} to "Nbr de loups garous blancs"
					set {_name} to "Wwerewolf"
				else if {_s} is 22:
					set {_item} to "1 coal"
					set {_displayname} to "Nbr d'infects pere des loups"
					set {_name} to "Owerewolf"
				else if {_s} is 23:
					set {_item} to "1 book"
					set {_displayname} to "Nbr d'assassins"
					set {_name} to "killer"
				else if {_s} is 24:
					set {_item} to "1 vine"
					set {_displayname} to "Nbr d'enfants sauvages"
					set {_name} to "wildchild"
				else if {_s} is 25:
					set {_item} to "1 clock"
					set {_displayname} to "Nbr de voleurs"
					set {_name} to "thief"
				else if {_s} is 28:
					set {_item} to "1 paper"
					set {_displayname} to "Nbr de loups-garous amnésiques"
					set {_name} to "Awerewolf"
				else if {_s} is 29:
					set {_item} to "1 golden apple"
					set {_displayname} to "Nbr de salvateurs"
					set {_name} to "savior"
				if {_s} is not 16:
					make a gui slot {_s} of {_p} with ({_item}  parsed as item) named "&6&l%{_displayname}%: %{lg::config::%{_name}%::size}%" with lore "&f&lClique gauche: &a+1 " and "&f&lClique droit: &c-1" to run:
						if gui-click-type is left mouse button:
							add 1 to {lg::config::%{_name}%::size}
						else if gui-click-type is right mouse button:
							if {lg::config::%{_name}%::size} is higher than 0:
								remove 1 from {lg::config::%{_name}%::size}
						lgu_config({_p},"roles")
				add 1 to {_s}
			make a gui slot 16 of {_p} with 1 bow named "&6&lNbr de cupidons &r1 max: &6&l%{lg::config::cupidon::size}%" with lore "&f&lClique gauche: &a+1 " and "&f&lClique droit: &c-1" to run:
				if gui-click-type is left mouse button:
					if {lg::config::cupidon::size} is smaller than 1:
						add 1 to {lg::config::cupidon::size}
						set {lg::config::randomlover} to false
				else if gui-click-type is right mouse button:
					if {lg::config::cupidon::size} is higher than 0:
						remove 1 from {lg::config::cupidon::size}
				lgu_config({_p},"roles")
		else:
			set {lg::config::villager::size} to 1

			make a gui slot 44 of {_p} with 1 compass named "&eMode nombre" with lore "&7Vous pouvez préciser le nombre exacte de chaque " and "&7rôle présent dans la partie" to run:
				set {lg::config::random} to false
				lgu_config({_p},"roles")
			make a gui slot 0 of {_p} with a map named "&7&lRevenir en arrière -->" to run:
				lgu_config({_p},"Menu")
			set {_s} to 10
			loop 16 times:
				if {_s} is 17:
					set {_s} to 19
				if {_s} is 26:
					set {_s} to 28
				if {_s} is 10:
					set {_displayname} to "Villageois"
					set {_name} to "villager"
				else if {_s} is 11:
					set {_displayname} to "Inquisiteur"
					set {_name} to "inquisitor"
				else if {_s} is 12:
					set {_displayname} to "Sorciere"
					set {_name} to "witch"
				else if {_s} is 13:
					set {_displayname} to "Oracle"
					set {_name} to "oracle"
				else if {_s} is 14:
					set {_displayname} to "Petite fille"
					set {_name} to "girl"
				else if {_s} is 15:
					set {_displayname} to "Ancien"
					set {_name} to "oldone"
				else if {_s} is 16:
					set {_displayname} to "Cupidon"
					set {_name} to "cupidon"
				else if {_s} is 19:
					set {_displayname} to "Renard"
					set {_name} to "fox"
				else if {_s} is 20:
					set {_displayname} to "Loups garou"
					set {_name} to "werewolf"
				else if {_s} is 21:
					set {_displayname} to "Loups garou blanc"
					set {_name} to "Wwerewolf"
				else if {_s} is 22:
					set {_displayname} to "Infects pere des loups"
					set {_name} to "Owerewolf"
				else if {_s} is 23:
					set {_displayname} to "Assassins"
					set {_name} to "killer"
				else if {_s} is 24:
					set {_displayname} to "Enfants sauvage"
					set {_name} to "wildchild"
				else if {_s} is 25:
					set {_displayname} to "Voleur"
					set {_name} to "thief"
				else if {_s} is 28:
					set {_displayname} to "Loup-garou amnésique"
					set {_name} to "Awerewolf"
				else if {_s} is 29:
					set {_displayname} to "Salvateur"
					set {_name} to "savior"

				if {_s} is not 10:
					if {lg::config::%{_name}%::size} is 0:
						make a gui slot {_s} of {_p} with 1 red wool named "&6&l%{_displayname}%&7: &cDésactivé" with lore "&f&lClique gauche: &aActiver " and "&f&lClique droit: &cDésactiver" to run:
							if gui-click-type is left mouse button:
								set {lg::config::%{_name}%::size} to 1
								if {_name} is "cupidon":
									set {lg::config::randomlover} to false
								lgu_config({_p},"roles")
					else:
						make a gui slot {_s} of {_p} with 1 light green wool named "&6&l%{_displayname}%&7: &aActivé" with lore "&f&lClique gauche: &aActiver " and "&f&lClique droit: &cDésactiver" to run:
							if gui-click-type is right mouse button:
								set {lg::config::%{_name}%::size} to 0
								lgu_config({_p},"roles")
				add 1 to {_s}
			make a gui slot 10 of {_p} with 1 green wool named "&6&lVillageois&7: &aActivé" with lore "&7Ne peut pas être désactivé, mais les villageois" and "&7ne seront ajoutés que si tout les autres" and "&7rôles activés ont été distribués."
	else if {_t} is "extras":
		open virtual chest inventory with size 4 with name "&lConfigurer les rôles" to {_p}
		make a gui slot 0 of {_p} with a map named "&7&lRevenir en arrière -->" to run:
			lgu_config({_p},"roles")
		make a gui slot 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 28, 29, 30, 31, 32, 33, 34 and 35 of {_p} with 1 gray stained glass pane named "&f"
		if {lg::config::random} is false:
			make a gui slot 10 of {_p} with 1 enchanting table named "&6&lVoyante: %{lg::config::seer::size}%" with lore "&f&lClique gauche: &a+1 " and "&f&lClique droit: &c-1" to run:
				if gui-click-type is left mouse button:
					add 1 to {lg::config::seer::size}
				else if gui-click-type is right mouse button:
					if {lg::config::seer::size} is higher than 0:
						remove 1 from {lg::config::seer::size}
				lgu_config({_p},"extras")
			make a gui slot 11 of {_p} with 1 feather named "&6&lAnge: %{lg::config::angel::size}%" with lore "&f&lClique gauche: &a+1 " and "&f&lClique droit: &c-1" to run:
				if gui-click-type is left mouse button:
					add 1 to {lg::config::angel::size}
				else if gui-click-type is right mouse button:
					if {lg::config::angel::size} is higher than 0:
						remove 1 from {lg::config::angel::size}
				lgu_config({_p},"extras")
			make a gui slot 12 of {_p} with 1 iron sword named "&6&lChasseur: &cDésactivé" with lore "&f&lNe marche pas"

		else:
			if {lg::config::seer::size} is 0:
				make a gui slot 10 of {_p} with 1 red wool named "&6&lVoyante&7: &cDésactivé" with lore "&f&lClique gauche: &aActiver " and "&f&lClique droit: &cDésactiver" to run:
					if gui-click-type is left mouse button:
						set {lg::config::seer::size} to 1
						lgu_config({_p},"extras")
			else:
				make a gui slot 10 of {_p} with 1 light green wool named "&6&lVoyante&7: &aActivé" with lore "&f&lClique gauche: &aActiver " and "&f&lClique droit: &cDésactiver" to run:
					if gui-click-type is right mouse button:
						set {lg::config::seer::size} to 0
						lgu_config({_p},"extras")
			if {lg::config::angel::size} is 0:
				make a gui slot 11 of {_p} with 1 red wool named "&6&lAnge&7: &cDésactivé" with lore "&f&lClique gauche: &aActiver " and "&f&lClique droit: &cDésactiver" to run:
					if gui-click-type is left mouse button:
						set {lg::config::angel::size} to 1
						lgu_config({_p},"extras")
			else:
				make a gui slot 11 of {_p} with 1 light green wool named "&6&lAnge&7: &aActivé" with lore "&f&lClique gauche: &aActiver " and "&f&lClique droit: &cDésactiver" to run:
					if gui-click-type is right mouse button:
						set {lg::config::angel::size} to 0
						lgu_config({_p},"extras")
			if {lg::config::hunter::size} is 0:
				make a gui slot 12 of {_p} with 1 red wool named "&6&lChasseur&7: &cDésactivé" with lore "&f&lNe marche pas"
			else:
				make a gui slot 12 of {_p} with 1 light green wool named "&6&lChasseur&7: &aActivé" with lore "&f&lClique gauche: &aActiver " and "&f&lClique droit: &cDésactiver" to run:
					if gui-click-type is right mouse button:
						set {lg::config::hunter::size} to 0
						lgu_config({_p},"extras")
		if {lg::config::randomlover} is true:
			make a gui slot 25 of {_p} with 1 red tulip named "&dAmoureux aléatoire&7: &aActivé" with lore "&7Définit les amoureur aléatoirement à la distrubution des rôles" and "&7Si activé, Cupidon est automatiquement désactivé" to run:
				set {lg::config::randomlover} to false
				lgu_config({_p},"extras")
		else:
			make a gui slot 25 of {_p} with 1 red tulip named "&dAmoureux aléatoire&7: &cDésactivé" with lore "&7Définit les amoureur aléatoirement à la distrubution des rôles" and "&7Si activé, Cupidon est automatiquement désactivé" to run:
				set {lg::config::randomlover} to true
				set {lg::config::cupidon::size} to 0
				lgu_config({_p},"extras")
	else if {_t} is equal to "pvp":
		make a gui slot 1, 2, 3, 4, 5, 6, 7, 8, 9, 13, 17, 18, 19, 20, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34 and 35 of {_p} with 1 gray stained glass pane named "&f"
		make a gui slot 21 and 23 of {_p} with 1 white stained glass pane
		if {lg::config::pvp} is 0:
			make a gui slot 22 of {_p} with 1 diamond sword named "&eDebut du pvp" with lore "&7Le pvp commencera " and "&7au &6début de la partie"
		else:
			make a gui slot 22 of {_p} with 1 diamond sword named "&eDebut du pvp" with lore "&7Le pvp commencera " and "&7au bout de &6%{lg::config::pvp}% &7minutes"
		make a gui slot 0 of {_p} with a map named "&7&lRevenir en arrière -->" to run:
			lgu_config({_p},"Menu")

		make a gui slot 14 of {_p} with 1 light green stained glass pane named "&a&l+1" to run:
			add 1 to {lg::config::pvp}
			lgu_config({_p},"pvp")
		make a gui slot 15 of {_p} with 1 light green stained glass pane named "&a&l+5" to run:
			add 5 to {lg::config::pvp}
			lgu_config({_p},"pvp")
		make a gui slot 16 of {_p} with 1 light green stained glass pane named "&a&l+10" to run:
			add 10 to {lg::config::pvp}
			lgu_config({_p},"pvp")
		make a gui slot 12 of {_p} with 1 red stained glass pane named "&c&l-1" to run:
			if {lg::config::pvp} is higher than 0:
				remove 1 from {lg::config::pvp}
				lgu_config({_p},"pvp")
		make a gui slot 11 of {_p} with 1 red stained glass pane named "&c&l-5" to run:
			if {lg::config::pvp} is higher than 4:
				remove 5 from {lg::config::pvp}
				lgu_config({_p},"pvp")
			else:
				set {lg::config::pvp} to 0
				lgu_config({_p},"pvp")
		make a gui slot 10 of {_p} with 1 red stained glass pane named "&c&l-10" to run:
			if {lg::config::pvp} is higher than 9:
				remove 10 from {lg::config::pvp}
				lgu_config({_p},"pvp")
			else:
				set {lg::config::pvp} to 0
				lgu_config({_p},"pvp")
	else if {_t} is equal to "dborder":
		make a gui slot 1, 2, 3, 4, 5, 6, 7, 8, 9, 13, 17, 18, 19, 20, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34 and 35 of {_p} with 1 gray stained glass pane named "&f"
		make a gui slot 21 and 23 of {_p} with 1 white stained glass pane
		make a gui slot 22 of {_p} with 1 barrier named "&eBordure du départ" with lore "&7La bordure du départ actuelle est de &6+%{lg::config::dborder} / 2%/-%{lg::config::dborder} / 2%"
		make a gui slot 0 of {_p} with a map named "&7&lRevenir en arrière -->" to run:
			lgu_config({_p},"Menu")

		make a gui slot 14 of {_p} with 1 light green stained glass pane named "&a&l+50" to run:
			add 50 to {lg::config::dborder}
			lgu_config({_p},"dborder")
		make a gui slot 15 of {_p} with 1 light green stained glass pane named "&a&l+100" to run:
			add 100 to {lg::config::dborder}
			lgu_config({_p},"dborder")
		make a gui slot 16 of {_p} with 1 light green stained glass pane named "&a&l+500" to run:
			add 500 to {lg::config::dborder}
			lgu_config({_p},"dborder")
		make a gui slot 12 of {_p} with 1 red stained glass pane named "&c&l-50" to run:
			if {lg::config::dborder} is higher than 549:
				remove 50 from {lg::config::dborder}
				lgu_config({_p},"dborder")
		make a gui slot 11 of {_p} with 1 red stained glass pane named "&c&l-100" to run:
			if {lg::config::dborder} is higher than 599:
				remove 100 from {lg::config::dborder}
				lgu_config({_p},"dborder")
			else:
				set {lg::config::dborder} to 500
				lgu_config({_p},"dborder")
		make a gui slot 10 of {_p} with 1 red stained glass pane named "&c&l-500" to run:
			if {lg::config::dborder} is higher than 999:
				remove 500 from {lg::config::dborder}
				lgu_config({_p},"dborder")
			else:
				set {lg::config::dborder} to 500
				lgu_config({_p},"dborder")
	else if {_t} is equal to "fborder":
		make a gui slot 1, 2, 3, 4, 5, 6, 7, 8, 9, 13, 17, 18, 19, 20, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34 and 35 of {_p} with 1 gray stained glass pane named "&f"
		make a gui slot 21 and 23 of {_p} with 1 white stained glass pane
		make a gui slot 22 of {_p} with 1 barrier named "&eBordure finale" with lore "&7La bordure finale actuelle est de &6+%{lg::config::fborder} / 2%/-%{lg::config::fborder} / 2%"
		make a gui slot 0 of {_p} with a map named "&7&lRevenir en arrière -->" to run:
			lgu_config({_p},"Menu")

		make a gui slot 14 of {_p} with 1 light green stained glass pane named "&a&l+50" to run:
			add 50 to {lg::config::fborder}
			lgu_config({_p},"fborder")
		make a gui slot 15 of {_p} with 1 light green stained glass pane named "&a&l+100" to run:
			add 100 to {lg::config::fborder}
			lgu_config({_p},"fborder")
		make a gui slot 16 of {_p} with 1 light green stained glass pane named "&a&l+500" to run:
			add 500 to {lg::config::fborder}
			lgu_config({_p},"fborder")
		make a gui slot 12 of {_p} with 1 red stained glass pane named "&c&l-50" to run:
			if {lg::config::fborder} is higher than 149:
				remove 50 from {lg::config::fborder}
				lgu_config({_p},"fborder")
			else:
				set {lg::config::fborder} to 100
				lgu_config({_p},"fborder")
		make a gui slot 11 of {_p} with 1 red stained glass pane named "&c&l-100" to run:
			if {lg::config::fborder} is higher than 199:
				remove 100 from {lg::config::fborder}
				lgu_config({_p},"fborder")
			else:
				set {lg::config::fborder} to 100
				lgu_config({_p},"fborder")
		make a gui slot 10 of {_p} with 1 red stained glass pane named "&c&l-500" to run:
			if {lg::config::fborder} is higher than 599:
				remove 500 from {lg::config::fborder}
				lgu_config({_p},"dborder")
			else:
				set {lg::config::fborder} to 100
				lgu_config({_p},"fborder")
	else if {_t} is equal to "items":
		open virtual chest inventory with size 6 with name "&lConfigurer les items" to {_p}
		make a gui slot 36, 37, 38, 39, 40, 41, 42, 43, 44, 49, 50 and 51 of {_p} with 1 gray stained glass pane named "&f"
		make a gui slot 52 of {_p} with a map named "&7&lRevenir en arrière -->" to run:
			lgu_config({_p},"Menu")
		if {lg::items::items::*} is set:
			set {_s} to 27
			set {_i} to 1
			loop 9 times:
				if {lg::items::items::%{_i}%} is not air:
					make a gui slot {_s} of {_p} with {lg::items::items::%{_i}%}
				else:
					make a gui slot {_s} of {_p} with 1 light gray stained glass pane named "&f"
				add 1 to {_s}
				add 1 to {_i}
			set {_s} to 0
			loop 27 times:
				if {lg::items::items::%{_i}%} is not air:
					make a gui slot {_s} of {_p} with {lg::items::items::%{_i}%}
				else:
					make a gui slot {_s} of {_p} with 1 light gray stained glass pane named "&f"
				add 1 to {_s}
				add 1 to {_i}
			if {lg::items::helmet} is not air:
				make a gui slot 45 of {_p} with {lg::items::helmet}
			else:
				make a gui slot 45 of {_p} with light gray stained glass pane named "&f"
			if {lg::items::chestplate} is not air:
				make a gui slot 46 of {_p} with {lg::items::chestplate}
			else:
				make a gui slot 46 of {_p} with light gray stained glass pane named "&f"
			if {lg::items::leggings} is not air:
				make a gui slot 47 of {_p} with {lg::items::leggings}
			else:
				make a gui slot 47 of {_p} with light gray stained glass pane named "&f"
			if {lg::items::boots} is not air:
				make a gui slot 48 of {_p} with {lg::items::boots}
			else:
				make a gui slot 48 of {_p} with light gray stained glass pane named "&f"
		make a gui slot 53 of {_p} with a emerald block named "&eAjouter des items" with lore "" and "&a>> &lCliquez pour changer" to run:
			close {_p}'s inventory
			set {lg::%{_p}%::items} to "items"
			message "&2------------------------------------" to {_p}
			message "" to {_p}
			message "&8&l>> &aFaites &e/lg finish &apour sauvegarder les items de départ" to {_p}
			message "" to {_p}
			message "&2------------------------------------" to {_p}
			clear {_p}'s inventory
			if {lg::items::items::*} is set:
				set {_s} to 0
				loop {lg::items::items::*}:
					set slot {_s} of {_p}'s inventory to loop-value
					add 1 to {_s}
				set {_p}'s helmet to {lg::items::helmet}
				set {_p}'s chestplate to {lg::items::chestplate}
				set {_p}'s leggings to {lg::items::leggings}
				set {_p}'s boots to {lg::items::boots}
	else if {_t} is equal to "tborder":
		make a gui slot 1, 2, 3, 4, 5, 6, 7, 8, 9, 13, 17, 18, 19, 20, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34 and 35 of {_p} with 1 gray stained glass pane named "&f"
		make a gui slot 21 and 23 of {_p} with 1 white stained glass pane
		if {lg::config::tborder} is not equal to 0:
			make a gui slot 22 of {_p} with 1 barrier named "&eTemps avant la bordure" with lore "&7La bordure commencera " and "&7à bouger au bout de " and "&6%{lg::config::tborder}% &7minutes"
		else:
			make a gui slot 22 of {_p} with 1 barrier named "&eTemps avant la bordure" with lore "&7La bordure commencera " and "&7à bouger &6dés le début du jeu"
		make a gui slot 0 of {_p} with a map named "&7&lRevenir en arrière -->" to run:
			lgu_config({_p},"Menu")

		make a gui slot 14 of {_p} with 1 light green stained glass pane named "&a&l+1" to run:
			add 1 to {lg::config::tborder}
			lgu_config({_p},"tborder")
		make a gui slot 15 of {_p} with 1 light green stained glass pane named "&a&l+5" to run:
			add 5 to {lg::config::tborder}
			lgu_config({_p},"tborder")
		make a gui slot 16 of {_p} with 1 light green stained glass pane named "&a&l+10" to run:
			add 10 to {lg::config::tborder}
			lgu_config({_p},"tborder")
		make a gui slot 12 of {_p} with 1 red stained glass pane named "&c&l-1" to run:
			if {lg::config::tborder} is higher than 0:
				remove 1 from {lg::config::tborder}
				lgu_config({_p},"tborder")
		make a gui slot 11 of {_p} with 1 red stained glass pane named "&c&l-5" to run:
			if {lg::config::tborder} is higher than 4:
				remove 5 from {lg::config::tborder}
				lgu_config({_p},"tborder")
			else:
				set {lg::config::tborder} to 0
				lgu_config({_p},"tborder")
		make a gui slot 10 of {_p} with 1 red stained glass pane named "&c&l-10" to run:
			if {lg::config::tborder} is higher than 9:
				remove 10 from {lg::config::tborder}
				lgu_config({_p},"tborder")
			else:
				set {lg::config::tborder} to 0
				lgu_config({_p},"tborder")
	else if {_t} is equal to "rtime":
		make a gui slot 1, 2, 3, 4, 5, 6, 7, 8, 9, 13, 17, 18, 19, 20, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34 and 35 of {_p} with 1 gray stained glass pane named "&f"
		make a gui slot 21 and 23 of {_p} with 1 white stained glass pane
		if {lg::config::rtime} is not equal to 0:
			make a gui slot 22 of {_p} with 1 book named "&eRévélation des rôles" with lore "&7Les rôles sont révélés " and "&7au bout de &6%{lg::config::rtime}% &7minutes"
		else:
			make a gui slot 22 of {_p} with 1 book named "&eRévélation des rôles" with lore "&7Les rôles sont révélés " and "&7au &6début de la parite"
		make a gui slot 0 of {_p} with a map named "&7&lRevenir en arrière -->" to run:
			lgu_config({_p},"Menu")

		make a gui slot 14 of {_p} with 1 light green stained glass pane named "&a&l+1" to run:
			add 1 to {lg::config::rtime}
			lgu_config({_p},"rtime")
		make a gui slot 15 of {_p} with 1 light green stained glass pane named "&a&l+5" to run:
			add 5 to {lg::config::rtime}
			lgu_config({_p},"rtime")
		make a gui slot 16 of {_p} with 1 light green stained glass pane named "&a&l+10" to run:
			add 10 to {lg::config::rtime}
			lgu_config({_p},"rtime")
		make a gui slot 12 of {_p} with 1 red stained glass pane named "&c&l-1" to run:
			if {lg::config::rtime} is higher than 0:
				remove 1 from {lg::config::rtime}
				lgu_config({_p},"rtime")
		make a gui slot 11 of {_p} with 1 red stained glass pane named "&c&l-5" to run:
			if {lg::config::rtime} is higher than 4:
				remove 5 from {lg::config::rtime}
				lgu_config({_p},"rtime")
			else:
				set {lg::config::rtime} to 0
				lgu_config({_p},"rtime")
		make a gui slot 10 of {_p} with 1 red stained glass pane named "&c&l-10" to run:
			if {lg::config::rtime} is higher than 9:
				remove 10 from {lg::config::rtime}
				lgu_config({_p},"rtime")
			else:
				set {lg::config::rtime} to 0
				lgu_config({_p},"rtime")
	else if {_t} is equal to "death":
		open virtual chest inventory with size 5 with name "&lConfigurer les items" to {_p}
		make a gui slot 36, 37, 38, 39, 40, 41 and 42 of {_p} with 1 gray stained glass pane named "&f"
		make a gui slot 43 of {_p} with a map named "&7&lRevenir en arrière -->" to run:
			lgu_config({_p},"Menu")
		if {lg::deathitems::items::*} is set:
			set {_s} to 27
			set {_i} to 1
			loop 9 times:
				if {lg::deathitems::items::%{_i}%} is not air:
					make a gui slot {_s} of {_p} with {lg::deathitems::items::%{_i}%}
				else:
					make a gui slot {_s} of {_p} with 1 light gray stained glass pane named "&f"
				add 1 to {_s}
				add 1 to {_i}
			set {_s} to 0
			loop 27 times:
				if {lg::deathitems::items::%{_i}%} is not air:
					make a gui slot {_s} of {_p} with {lg::deathitems::items::%{_i}%}
				else:
					make a gui slot {_s} of {_p} with 1 light gray stained glass pane named "&f"
				add 1 to {_s}
				add 1 to {_i}
		make a gui slot 44 of {_p} with a emerald block named "&eAjouter des items" with lore "" and "&a>> &lCliquez pour changer" to run:
			close {_p}'s inventory
			set {lg::%{_p}%::items} to "death"
			message "&2------------------------------------" to {_p}
			message "" to {_p}
			message "&8&l>> &aFaites &e/lg finish &apour sauvegarder les items de mort" to {_p}
			message "" to {_p}
			message "&2------------------------------------" to {_p}
			clear {_p}'s inventory
			if {lg::deathitems::items::*} is set:
				set {_s} to 0
				loop {lg::deathitems::items::*}:
					set slot {_s} of {_p}'s inventory to loop-value
					add 1 to {_s}
	else if {_t} is equal to "rules":
		open virtual chest inventory with size 3 with name "&lConfigurer les règles" to {_p}
		make a gui slot 0 of {_p} with a map named "&7&lRevenir en arrière -->" to run:
			lgu_config({_p},"Menu")
		make a gui slot 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 19, 20, 21, 22, 23, 24, 25 and 26 of {_p} with 1 gray stained glass pane named "&f"
		if {lg::config::optimining} is true:
			make a gui slot 10 of {_p} with 1 diamond ore named "&6&lMinage optimisé&7: &aActivé" to run:
				set {lg::config::optimining} to false
				lgu_config({_p},"rules")
		else:
			make a gui slot 10 of {_p} with 1 diamond ore named "&6&lMinage optimisé&7: &cDésactivé" to run:
				set {lg::config::optimining} to true
				lgu_config({_p},"rules")
		if {lg::config::towers} is true:
			make a gui slot 11 of {_p} with 1 dirt named "&6&lTower&7: &aActivé" to run:
				set {lg::config::towers} to false
				lgu_config({_p},"rules")
		else:
			make a gui slot 11 of {_p} with 1 dirt named "&6&lTower&7: &cDésactivé" to run:
				set {lg::config::towers} to true
				lgu_config({_p},"rules")
		if {lg::config::nether} is true:
			make a gui slot 12 of {_p} with 1 netherrack named "&6&lNether&7: &aActivé" to run:
				set {lg::config::nether} to false
				lgu_config({_p},"rules")
		else:
			make a gui slot 12 of {_p} with 1 netherrack named "&6&lNether&7: &cDésactivé" to run:
				set {lg::config::nether} to true
				lgu_config({_p},"rules")
		if {lg::config::rod} is true:
			make a gui slot 13 of {_p} with 1 fishing rod named "&6&lFishing Rod&7: &aActivé" to run:
				set {lg::config::rod} to false
				lgu_config({_p},"rules")
		else:
			make a gui slot 13 of {_p} with 1 fishing rod named "&6&lFishing Rod&7: &cDésactivé" to run:
				set {lg::config::rod} to true
				lgu_config({_p},"rules")
		if {lg::config::hide} is true:
			make a gui slot 14 of {_p} with 1 ender pearl named "&6&lComposition cachée&7: &aActivé" to run:
				set {lg::config::hide} to false
				lgu_config({_p},"rules")
		else:
			make a gui slot 14 of {_p} with 1 ender pearl named "&6&lComposition cachée&7: &cDésactivé" to run:
				set {lg::config::hide} to true
				lgu_config({_p},"rules")
		if {lg::config::apple} is false:
			make a gui slot 15 of {_p} with 1 apple named "&6&lDrop des pommes custom&7: &cDésactivé" with lore "&7Ratio de drops: &b%{lg::config::applerate}%%%" and "" and "&8&l>> &f&lClique gauche: &aActiver" and "&8&l>> &f&lClique droit: &bChanger la limite" to run:
				if gui-click-type is left mouse button:
					set {lg::config::apple} to true
					lgu_config({_p},"rules")
				else if gui-click-type is right mouse button:
					lgu_config({_p},"applerate")
		else:
			make a gui slot 15 of {_p} with 1 apple named "&6&lDrop des pommes custom&7: &aActivé" with lore "&7Ratio de drops: &b%{lg::config::applerate}%%%" and "" and "&8&l>> &f&lClique gauche: &cDésactivé" and "&8&l>> &f&lClique droit: &bChanger la limite" to run:
				if gui-click-type is left mouse button:
					set {lg::config::apple} to false
					lgu_config({_p},"rules")
				else if gui-click-type is right mouse button:
					lgu_config({_p},"applerate")
		if {lg::config::flint} is false:
			make a gui slot 16 of {_p} with 1 flint named "&6&lDrop des silex custom&7: &cDésactivé" with lore "&7Ratio de drops: &b%{lg::config::flintrate}%%%" and "" and "&8&l>> &f&lClique gauche: &aActiver" and "&8&l>> &f&lClique droit: &bChanger la limite" to run:
				if gui-click-type is left mouse button:
					set {lg::config::flint} to true
					lgu_config({_p},"rules")
				else if gui-click-type is right mouse button:
					lgu_config({_p},"flintrate")
		else:
			make a gui slot 16 of {_p} with 1 flint named "&6&lDrop des silex custom&7: &aActivé" with lore "&7Ratio de drops: &b%{lg::config::flintrate}%%%" and "" and "&8&l>> &f&lClique gauche: &cDésactivé" and "&8&l>> &f&lClique droit: &bChanger la limite" to run:
				if gui-click-type is left mouse button:
					set {lg::config::flint} to false
					lgu_config({_p},"rules")
				else if gui-click-type is right mouse button:
					lgu_config({_p},"flintrate")
	else if {_t} is equal to "scenar":
		open virtual chest inventory with size 3 with name "&lConfigurer les scénarios" to {_p}
		make a gui slot 0 of {_p} with a map named "&7&lRevenir en arrière -->" to run:
			lgu_config({_p},"Menu")
		make a gui slot 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 19, 20, 21, 22, 23, 24, 25 and 26 of {_p} with 1 gray stained glass pane named "&f"
		if {lg::config::diamondlimit} is false:
			make a gui slot 10 of {_p} with 1 diamond named "&6&lDiamondLimit&7: &cDésactivé" with lore "&7Nombre de diamants: &b%{lg::config::diamondlimitsize}%" and "" and "&8&l>> &f&lClique gauche: &aActiver" and "&8&l>> &f&lClique droit: &bChanger la limite" to run:
				if gui-click-type is left mouse button:
					set {lg::config::diamondlimit} to true
					lgu_config({_p},"scenar")
				else if gui-click-type is right mouse button:
					lgu_config({_p},"diamondlimit")
		else:
			make a gui slot 10 of {_p} with 1 diamond named "&6&lDiamondLimit&7: &aActivé" with lore "&7Nombre de diamants: &b%{lg::config::diamondlimitsize}%" and "" and "&8&l>> &f&lClique gauche: &cDésactivé" and "&8&l>> &f&lClique droit: &bChanger la limite" to run:
				if gui-click-type is left mouse button:
					set {lg::config::diamondlimit} to false
					lgu_config({_p},"scenar")
				else if gui-click-type is right mouse button:
					lgu_config({_p},"diamondlimit")
		if {lg::config::cutlean} is false:
			make a gui slot 11 of {_p} with 1 iron pickaxe named "&6&lCutClean&7: &cDésactivé" with lore "" and "" and "&a>> &lCliquez pour changer " to run:
				set {lg::config::cutlean} to true
				lgu_config({_p},"scenar")
		else:
			make a gui slot 11 of {_p} with 1 iron pickaxe named "&6&lCutClean&7: &aActivé" with lore "" and "" and "&a>> &lCliquez pour changer " to run:
				set {lg::config::cutlean} to false
				lgu_config({_p},"scenar")
		if {lg::config::nofire} is false:
			make a gui slot 12 of {_p} with 1 flint and steel named "&6&lNoFire&7: &cDésactivé" with lore "" and "" and "&a>> &lCliquez pour changer " to run:
				set {lg::config::nofire} to true
				lgu_config({_p},"scenar")
		else:
			make a gui slot 12 of {_p} with 1 flint and steel named "&6&lNoFire&7: &aActivé" with lore "" and "" and "&a>> &lCliquez pour changer " to run:
				set {lg::config::nofire} to false
				lgu_config({_p},"scenar")
		if {lg::config::meetup} is true:
			make a gui slot 13 of {_p} with 1 iron chestplate named "&6&lMeetup&7: &aActivé" with lore "&7Cette option ne change que certains objets donnés" and "&7merci de modifier les items de départs pour un bon meetup" to run:
				set {lg::config::meetup} to false
				lgu_config({_p},"scenar")
		else:
			make a gui slot 13 of {_p} with 1 iron chestplate named "&6&lMeetup&7: &cDésactivé" with lore "&7Cette option ne change que certains objets donnés" and "&7merci de modifier les items de départs pour un bon meetup" to run:
				set {lg::config::meetup} to true
				lgu_config({_p},"scenar")
		if {lg::config::horse} is true:
			make a gui slot 14 of {_p} with 1 saddle named "&6&lChevaux&7: &aActivé" to run:
				set {lg::config::horse} to false
				lgu_config({_p},"scenar")
		else:
			make a gui slot 14 of {_p} with 1 saddle named "&6&lChevaux&7: &cDésactivé" to run:
				set {lg::config::horse} to true
				lgu_config({_p},"scenar")
		if {lg::config::nodeathbeforepvp} is true:
			make a gui slot 15 of {_p} with 1 bone named "&6&lPas de mort avant le pvp&7: &aActivé" with lore "&7Les joueurs sont bloqués à 1 demi coeur." to run:
				set {lg::config::nodeathbeforepvp} to false
				lgu_config({_p},"scenar")
		else:
			make a gui slot 15 of {_p} with 1 bone named "&6&lPas de mort avant le pvp&7: &cDésactivé" with lore "&7Les joueurs sont bloqués à 1 demi coeur." to run:
				set {lg::config::nodeathbeforepvp} to true
				lgu_config({_p},"scenar")
		if {lg::config::finalheal} is true:
			make a gui slot 16 of {_p} with 1 golden apple named "&6&lFinal Heal&7: &aActivé" with lore "&7Remets tous les joueurs au max de leurs vie au pvp" to run:
				set {lg::config::finalheal} to false
				lgu_config({_p},"scenar")
		else:
			make a gui slot 16 of {_p} with 1 golden apple named "&6&lFinal Heal&7: &cDésactivé" with lore "&7Remets tous les joueurs au max de leurs vie au pvp" to run:
				set {lg::config::finalheal} to true
				lgu_config({_p},"scenar")
	else if {_t} is equal to "diamondlimit":
		make a gui slot 1, 2, 3, 4, 5, 6, 7, 8, 9, 13, 17, 18, 19, 20, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34 and 35 of {_p} with 1 gray stained glass pane named "&f"
		make a gui slot 21 and 23 of {_p} with 1 white stained glass pane
		make a gui slot 22 of {_p} with 1 diamond named "&bLimite de diamant" with lore "&7La limite actuelle: &b%{lg::config::diamondlimitsize}%"
		make a gui slot 0 of {_p} with a map named "&7&lRevenir en arrière -->" to run:
			lgu_config({_p},"scenar")
		make a gui slot 10 of {_p} with 1 red stained glass pane named "&c&l-10" to run:
			remove 10 from {lg::config::diamondlimitsize}
			if {lg::config::diamondlimitsize} < 1:
				set {lg::config::diamondlimitsize} to 1
			lgu_config({_p},"diamondlimit")
		make a gui slot 11 of {_p} with 1 red stained glass pane named "&c&l-5" to run:
			remove 5 from {lg::config::diamondlimitsize}
			if {lg::config::diamondlimitsize} < 1:
				set {lg::config::diamondlimitsize} to 1
			lgu_config({_p},"diamondlimit")
		make a gui slot 12 of {_p} with 1 red stained glass pane named "&c&l-1" to run:
			remove 1 from {lg::config::diamondlimitsize}
			if {lg::config::diamondlimitsize} < 0:
				set {lg::config::diamondlimitsize} to 1
			lgu_config({_p},"diamondlimit")
		make a gui slot 14 of {_p} with 1 light green stained glass pane named "&a&l+1" to run:
			add 1 to {lg::config::diamondlimitsize}
			lgu_config({_p},"diamondlimit")
		make a gui slot 15 of {_p} with 1 light green stained glass pane named "&a&l+5" to run:
			add 5 to {lg::config::diamondlimitsize}
			lgu_config({_p},"diamondlimit")
		make a gui slot 16 of {_p} with 1 light green stained glass pane named "&a&l+10" to run:
			add 10 to {lg::config::diamondlimitsize}
			lgu_config({_p},"diamondlimit")
	else if {_t} is equal to "applerate":
		make a gui slot 1, 2, 3, 4, 5, 6, 7, 8, 9, 13, 17, 18, 19, 20, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34 and 35 of {_p} with 1 gray stained glass pane named "&f"
		make a gui slot 21 and 23 of {_p} with 1 white stained glass pane
		make a gui slot 22 of {_p} with 1 apple named "&bRatio du drops de pommes" with lore "&7Drop actuel: &b%{lg::config::applerate}%%%"
		make a gui slot 0 of {_p} with a map named "&7&lRevenir en arrière -->" to run:
			lgu_config({_p},"rules")
		make a gui slot 10 of {_p} with 1 red stained glass pane named "&c&l-10" to run:
			remove 10 from {lg::config::applerate}
			if {lg::config::applerate} < 0:
				set {lg::config::applerate} to 0
			lgu_config({_p},"applerate")
		make a gui slot 11 of {_p} with 1 red stained glass pane named "&c&l-5" to run:
			remove 5 from {lg::config::applerate}
			if {lg::config::applerate} < 0:
				set {lg::config::applerate} to 0
			lgu_config({_p},"applerate")
		make a gui slot 12 of {_p} with 1 red stained glass pane named "&c&l-1" to run:
			remove 1 from {lg::config::applerate}
			if {lg::config::applerate} < 0:
				set {lg::config::applerate} to 0
			lgu_config({_p},"applerate")
		make a gui slot 14 of {_p} with 1 light green stained glass pane named "&a&l+1" to run:
			add 1 to {lg::config::applerate}
			if {lg::config::applerate} > 100:
				set {lg::config::applerate} to 100
			lgu_config({_p},"applerate")
		make a gui slot 15 of {_p} with 1 light green stained glass pane named "&a&l+5" to run:
			add 5 to {lg::config::applerate}
			if {lg::config::applerate} > 100:
				set {lg::config::applerate} to 100
			lgu_config({_p},"applerate")
		make a gui slot 16 of {_p} with 1 light green stained glass pane named "&a&l+10" to run:
			add 10 to {lg::config::applerate}
			if {lg::config::applerate} > 100:
				set {lg::config::applerate} to 100
			lgu_config({_p},"applerate")
	else if {_t} is equal to "flintrate":
		make a gui slot 1, 2, 3, 4, 5, 6, 7, 8, 9, 13, 17, 18, 19, 20, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34 and 35 of {_p} with 1 gray stained glass pane named "&f"
		make a gui slot 21 and 23 of {_p} with 1 white stained glass pane
		make a gui slot 22 of {_p} with 1 flint named "&bRatio du drops des silex" with lore "&7Drop actuel: &b%{lg::config::flintrate}%%%"
		make a gui slot 0 of {_p} with a map named "&7&lRevenir en arrière -->" to run:
			lgu_config({_p},"rules")
		make a gui slot 10 of {_p} with 1 red stained glass pane named "&c&l-10" to run:
			remove 10 from {lg::config::flintrate}
			if {lg::config::flintrate} < 0:
				set {lg::config::flintrate} to 0
			lgu_config({_p},"flintrate")
		make a gui slot 11 of {_p} with 1 red stained glass pane named "&c&l-5" to run:
			remove 5 from {lg::config::flintrate}
			if {lg::config::flintrate} < 0:
				set {lg::config::flintrate} to 0
			lgu_config({_p},"flintrate")
		make a gui slot 12 of {_p} with 1 red stained glass pane named "&c&l-1" to run:
			remove 1 from {lg::config::flintrate}
			if {lg::config::flintrate} < 0:
				set {lg::config::flintrate} to 0
			lgu_config({_p},"flintrate")
		make a gui slot 14 of {_p} with 1 light green stained glass pane named "&a&l+1" to run:
			add 1 to {lg::config::flintrate}
			if {lg::config::flintrate} > 100:
				set {lg::config::flintrate} to 100
			lgu_config({_p},"flintrate")
		make a gui slot 15 of {_p} with 1 light green stained glass pane named "&a&l+5" to run:
			add 5 to {lg::config::flintrate}
			if {lg::config::flintrate} > 100:
				set {lg::config::flintrate} to 100
			lgu_config({_p},"flintrate")
		make a gui slot 16 of {_p} with 1 light green stained glass pane named "&a&l+10" to run:
			add 10 to {lg::config::flintrate}
			if {lg::config::flintrate} > 100:
				set {lg::config::flintrate} to 100
			lgu_config({_p},"flintrate")


function lgu_tp(p: player,b: boolean):
	set {_ok1} to false
	while {_ok1} is false:
		if {lg::current::border} is not set:
			set {_border} to {lg::config::dborder} / 2
		else:
			set {_border} to {lg::current::border}
		set {_x} to random number between (0 - {_border}) and {_border}
		set {_y} to 200
		set {_z} to random number between (0 - {_border}) and {_border}
		set {_loc} to location({_x}, {_y}, {_z}, world("%{lg::current::world}%"))
		set {_ok2} to false
		while {_ok2} is equal to false:
			if block at {_loc} is air:
				set y coordinate of {_loc} to (y coordinate of {_loc} - 1)
				if y coordinate of {_loc} is -1:
					set {_ok2} to true
			else:
				if block at {_loc} is not water:
					set {_ok2} to true
					set {_ok1} to true
				else:
					set {_ok2} to true
	if {_b} is false:
		set y coordinate of {_loc} to 200
	else:
		set y coordinate of {_loc} to (y coordinate of {_loc} + 1)
	teleport {_p} to {_loc}
function lgu_timer():
	set {_sec} to 0
	set {_min} to 0
	set {_sec2} to 0
	set {_min2} to 0
	set {_tborder} to {lg::config::tborder} * 60
	set {_tpvp} to {lg::config::pvp} * 60
	set {_trev} to {lg::config::rtime} * 60
	set {_day::*} to {lg::config::day2} split at "-"
	set {_day::1} to {_day::1} parsed as number
	set {_day::2} to {_day::2} parsed as number
	set {lg::current::day} to true
	set {_j} to true
	set {_totalsecond2} to {_day::1} * 60 + {_day::2}
	while {lg::info::start} is true:
		add 1 to {_sec}
		add 1 to {_sec2}
		if {_sec} is equal to 60:
			add 1 to {_min}
			set {_sec} to 0
		if {_sec2} is equal to 60:
			add 1 to {_min2}
			set {_sec2} to 0
		set {_totalsecond} to {_min} * 60 + {_sec}
		set {_totalsecond3} to {_min2} * 60 + {_sec2}
		set {_ndaysec2} to {_totalsecond2}
		remove {_totalsecond3} from {_ndaysec2}
		set {_ndaysec} to mod({_ndaysec2},60)
		remove {_ndaysec} from {_ndaysec2}
		set {_ndaysec2} to {_ndaysec2} / 60
		if {lg::current::day} is true:
			if {_ndaysec2} >= 10:
				if {_ndaysec} >= 10:
					set the text of id "LG_UHC_8" to "&7Nuit suivante: &c%{_ndaysec2}%:%{_ndaysec}%"
				else:
					set the text of id "LG_UHC_8" to "&7Nuit suivante: &c%{_ndaysec2}%:0%{_ndaysec}%"
			else:
				if {_ndaysec} >= 10:
					set the text of id "LG_UHC_8" to "&7Nuit suivante: &c0%{_ndaysec2}%:%{_ndaysec}%"
				else:
					set the text of id "LG_UHC_8" to "&7Nuit suivante: &c0%{_ndaysec2}%:0%{_ndaysec}%"
		else:
			if {_ndaysec2} >= 10:
				if {_ndaysec} >= 10:
					set the text of id "LG_UHC_8" to "&7Jour suivant: &c%{_ndaysec2}%:%{_ndaysec}%"
				else:
					set the text of id "LG_UHC_8" to "&7Jour suivant: &c%{_ndaysec2}%:0%{_ndaysec}%"
			else:
				if {_ndaysec} >= 10:
					set the text of id "LG_UHC_8" to "&7Jour suivant: &c0%{_ndaysec2}%:%{_ndaysec}%"
				else:
					set the text of id "LG_UHC_8" to "&7Jour suivant: &c0%{_ndaysec2}%:0%{_ndaysec}%"
		if {_min} is smaller than 60:
			if {_min} >= 10:
				if {_sec} >= 10:
					set the text of id "LG_UHC_9" to "&7Durée: &c%{_min}%:%{_sec}%"
				else:
					set the text of id "LG_UHC_9" to "&7Durée: &c%{_min}%:0%{_sec}%"
			else:
				if {_sec} >= 10:
					set the text of id "LG_UHC_9" to "&7Durée: &c0%{_min}%:%{_sec}%"
				else:
					set the text of id "LG_UHC_9" to "&7Durée: &c0%{_min}%:0%{_sec}%"
		else:
			set {_heure1} to mod({_min},60)
			set {_heure2} to {_min}
			remove {_heure1} from {_heure2}
			set {_heure2} to {_heure2} / 60
			if {_heure1} >= 10:
				if {_sec} >= 10:
					set the text of id "LG_UHC_9" to "&7Durée: &c%{_heure2}%:%{_heure1}%:%{_sec}%"
				else:
					set the text of id "LG_UHC_9" to "&7Durée: &c%{_heure2}%:%{_heure1}%:0%{_sec}%"
			else:
				if {_sec} >= 10:
					set the text of id "LG_UHC_9" to "&7Durée: &c%{_heure2}%:0%{_heure1}%:%{_sec}%"
				else:
					set the text of id "LG_UHC_9" to "&7Durée: &c%{_heure2}%:0%{_heure1}%:0%{_sec}%"
		if {_totalsecond} is smaller than {_tborder}:
			set {_calcul} to {_tborder} - {_totalsecond}
			set {_calculsec} to mod({_calcul}, 60)
			remove {_calculsec} from {_calcul}
			set {_calculmin} to {_calcul} / 60
			if {_calculmin} >= 10:
				if {_calculsec} >= 10:
					set the text of id "LG_UHC_7" to "&7Mur: &c%{_calculmin}%:%{_calculsec}%"
				else:
					set the text of id "LG_UHC_7" to "&7Mur: &c%{_calculmin}%:0%{_calculsec}%"
			else:
				if {_calculsec} >= 10:
					set the text of id "LG_UHC_7" to "&7Mur: &c0%{_calculmin}%:%{_calculsec}%"
				else:
					set the text of id "LG_UHC_7" to "&7Mur: &c0%{_calculmin}%:0%{_calculsec}%"
		else if {_totalsecond} is equal to {_tborder}:
			skellett delete id based score "LG_UHC_7" for stylish scoreboard with named "LG_UHC"
		if {_totalsecond} is smaller than {_tpvp}:
			set {_calcul} to {_tpvp} - {_totalsecond}
			set {_calculsec} to mod({_calcul}, 60)
			remove {_calculsec} from {_calcul}
			set {_calculmin} to {_calcul} / 60
			if {_calculmin} >= 10:
				if {_calculsec} >= 10:
					set the text of id "LG_UHC_6" to "&7Pvp: &c%{_calculmin}%:%{_calculsec}%"
				else:
					set the text of id "LG_UHC_6" to "&7Pvp: &c%{_calculmin}%:0%{_calculsec}%"
			else:
				if {_calculsec} >= 10:
					set the text of id "LG_UHC_6" to "&7Pvp: &c0%{_calculmin}%:%{_calculsec}%"
				else:
					set the text of id "LG_UHC_6" to "&7Pvp: &c0%{_calculmin}%:0%{_calculsec}%"
		else if {_totalsecond} is equal to {_tpvp}:
			skellett delete id based score "LG_UHC_6" for stylish scoreboard with named "LG_UHC"
		if {_totalsecond} is smaller than {_trev}:
			set {_calcul} to {_trev} - {_totalsecond}
			set {_calculsec} to mod({_calcul}, 60)
			remove {_calculsec} from {_calcul}
			set {_calculmin} to {_calcul} / 60
			if {_calculmin} >= 10:
				if {_calculsec} >= 10:
					set the text of id "LG_UHC_5" to "&7Révélation: &c%{_calculmin}%:%{_calculsec}%"
				else:
					set the text of id "LG_UHC_5" to "&7Révélation: &c%{_calculmin}%:0%{_calculsec}%"
			else:
				if {_calculsec} >= 10:
					set the text of id "LG_UHC_5" to "&7Révélation: &c0%{_calculmin}%:%{_calculsec}%"
				else:
					set the text of id "LG_UHC_5" to "&7Révélation: &c0%{_calculmin}%:0%{_calculsec}%"
		else if {_totalsecond} is equal to {_trev}:
			skellett delete id based score "LG_UHC_5" for stylish scoreboard with named "LG_UHC"
			set {lg::current::rev} to true
		if {lg::config::pvp} is not equal to 0:
			if {_min} is equal to ({lg::config::pvp} - 1):
				if {_sec} is equal to 55:
					lgu_eventmessage("pvp")
		if {lg::config::tborder} is not equal to 0:
			if {_min} is equal to ({lg::config::tborder} - 1):
				if {_sec} is equal to 55:
					lgu_eventmessage("border")
		if {lg::config::rtime} is not equal to 0:
			if {_min} is equal to ({lg::config::rtime} - 1):
				if {_sec} is equal to 55:
					lgu_eventmessage("roles")
		if {_min} is equal to 0:
			if {_sec} is equal to 30:
				set {lg::current::invincible} to false
				message "&8&l[&6&lLoup-garou&8&l] &7Les joueurs ne sont plus invincibles..." to all players
		if {lg::amoureux::2} is set:
			set {lg::amoureux::2}'s compass target to location of {lg::amoureux::1}
			set {lg::amoureux::1}'s compass target to location of {lg::amoureux::2}
		if {_min2} is 0:
			if {_sec2} is 45:
				if {lg::current::vote} is true:
					set {lg::current::vote} to false
					loop {lg::joueurs::*}:
						if {lg::%loop-value%::role} is "Ange" or "Inquisiteur":
							if {lg::vote::%loop-value%} is set:
								set {_1} to mod({lg::vote::%loop-value%},2)
								set {_2} to {lg::vote::%loop-value%} - {_1}
								set {_2} to {_2} / 2
								set {_max} to loop-value's max health
								set loop-value's max health to loop-value's max health + {_2}
								message "&8&l[&6&lLoup-garou&8&l] &7Vous avez été voté &3%{lg::vote::%loop-value%}% &7fois, vous avez donc gagné &c%{_2}% coeurs&7." to loop-value

					set {_vote} to -1
					loop {lg::vote::*}:
						if loop-value is higher than {_vote}:
							set {_vote} to loop-value
							set {_voteplayer} to loop-index parsed as player
					if {_voteplayer} is set:
						if {lg::%{_voteplayer}%::role} is not "Ange" or "Inquisiteur":
							set {_voteplayer}'s max health to 5
						message "&8&l[&6&lLoup-garou&8&l] &7Le joueur &3%{_voteplayer}% &7a été voté par le village, il perd la moitié de sa vie et reste bloqué à 5 coeurs jusqu'au prochain jour." to all players
						set {lg::current::voteplayer} to {_voteplayer}
					else:
						message "&8&l[&6&lLoup-garou&8&l] &7Aucun joueur n'a été voté par le village." to all players
					loop {lg::joueurs::*}:
						delete {lg::%loop-value%::vote}
						if {lg::%loop-value%::role} is "Voyante" or "Salvateur" or "Oracle" or "Inquisiteur":
							delete {lg::power::%loop-value%}
					delete {lg::vote::*}

		if {_min2} is {_day::1}:
			if {_sec2} is {_day::2}:
				set {_sec2} to 0
				set {_min2} to 0
				if {lg::current::day} is true:
					set {_seconde} to {_day::1} * 60
					add {_day::2} to {_seconde}
					set {_seconde} to "%{_seconde}% seconds" parsed as timespan
					message "&8&l[&6&lLoup-garou&8&l] &cDébut de la nuit" to all players
					if {lg::current::rev} is true:
						loop {lg::joueurs::*}:
							if {lg::%loop-value%::role} is "Petite fille":
								apply invisibility without any particles to loop-value for {_seconde}
								apply night vision without any particles to loop-value for {_seconde}
							else if {lg::%loop-value%::role} is "Loup-garou" or "Loup-garou blanc" or "Infect père des loups":
								apply strength without any particles to loop-value for {_seconde}
								apply night vision without any particles to loop-value for {_seconde}
							else if {lg::%loop-value%::role} is "Renard":
								apply night vision without any particles to loop-value for {_seconde}


					set {lg::current::day} to false
				else:
					set {_seconde} to {_day::1} * 60
					add {_day::2} to {_seconde}
					set {_seconde} to "%{_seconde}% seconds" parsed as timespan
					message "&8&l[&6&lLoup-garou&8&l] &aDébut de la journée" to all players
					if {lg::current::rev} is true:
						if {lg::current::voteplayer} is set:
							if {lg::%{lg::current::voteplayer}%::role} is not "Ange" or "Inquisiteur":
								if {lg::%{lg::current::voteplayer}%::role} is not "Loup-garou blanc":
									set {lg::current::voteplayer}'s max health to 10
								else:
									set {lg::current::voteplayer}'s max health to 12
						delete {lg::vote::*}
						message "" to all players
						message "&e------------------------------------" to all players
						message "" to all players
						loop all players:
							message "<cmd:/lg vote>&8&l[&aCliquez ici dans les 45 secondes pour voter&8&l]" to loop-player
						message "" to all players
						loop {lg::joueurs::*}:
							delete {lg::%loop-value%::vote}
							if {lg::%loop-value%::role} is "Voyante":
								message "<tooltip:&cCette action n'est réalisable qu'une fois par jour.><cmd:/lg power Voyante>&8&l[&5Cliquez ici dans les 45 secondes pour voir le rôle d'un joueur&8&l]" to loop-value
							else if {lg::%loop-value%::role} is "Oracle":
								message "<tooltip:&cCette action n'est réalisable qu'une fois par jour.><cmd:/lg power Oracle>&8&l[&5Cliquez ici dans les 45 secondes pour comparer deux joueurs&8&l]" to loop-value
							else if {lg::%loop-value%::role} is "Assassin":
								apply strength without any particles to loop-value for {_seconde}
							else if {lg::%loop-value%::role} is "Salvateur":
								message "<tooltip:&cCette action n'est réalisable qu'une fois par jour.><cmd:/lg power Salvateur>&8&l[&fCliquez ici dans les 45 secondes pour bénir un joueur&8&l]" to loop-value
						message "&e------------------------------------" to all players
						set {lg::current::vote} to true


					set {lg::current::day} to true

		loop {lg::joueurs::*}:
			set {_xx} to abs(x location of loop-value)
			set {_zz} to abs(z location of loop-value)
			if {_xx} is higher than 300:
				if {_xx} is smaller than 601:
					set {_x} to 300

			if {_xx} is higher than 600:
				if {_xx} is smaller than 1501:
					set {_x} to 600

			if {_xx} is higher than 1500:
				set {_x} to 1500
			if {_xx} is smaller than 301:
				set {_x} to 0
			if {_zz} is higher than 300:
				if {_zz} is smaller than 601:
					set {_z} to 300
			if {_zz} is higher than 600:
				if {_zz} is smaller than 1501:
					set {_z} to 600
			if {_zz} is higher than 1500:
				set {_z} to 1500
			if {_zz} is smaller than 301:
				set {_z} to 0
			if {_z} is higher than {_x}:
				set {_f} to {_z}
			else if {_x} is higher than {_z}:
				set {_f} to {_x}
			else:
				set {_f} to {_z}
			if {_f} is 0:
				show an actionbar with "&aEntre 0 et 300 blocs du spawn &fY: %round(y location of loop-value)%" to loop-value
			else if {_f} is 300:
				show an actionbar with "&2Entre 301 et 600 blocs du spawn &fY: %round(y location of loop-value)%" to loop-value
			else if {_f} is 600:
				show an actionbar with "&eEntre 601 et 1500 blocs du spawn &fY: %round(y location of loop-value)%" to loop-value
			else:
				show an actionbar with "&cPlus de 1500 blocs du spawn &fY: %round(y location of loop-value)%" to loop-value

		wait 1 second
function lgu_roles():
	if {lg::config::random} is equal to false:
		if {lg::config::villager::size} is not 0:
			loop {lg::config::villager::size} times:
				add "Villageois" to {_rolespossible::*}
		if {lg::config::witch::size} is not 0:
			loop {lg::config::witch::size} times:
				add "Sorcière" to {_rolespossible::*}
		if {lg::config::hunter::size} is not 0:
			loop {lg::config::hunter::size} times:
				add "Chasseur" to {_rolespossible::*}
		if {lg::config::seer::size} is not 0:
			loop {lg::config::seer::size} times:
				add "Voyante" to {_rolespossible::*}
		if {lg::config::girl::size} is not 0:
			loop {lg::config::girl::size} times:
				add "Petite fille" to {_rolespossible::*}
		if {lg::config::oldone::size} is not 0:
			loop {lg::config::oldone::size} times:
				add "Ancien" to {_rolespossible::*}
		if {lg::config::cupidon::size} is not 0:
			loop {lg::config::cupidon::size} times:
				add "Cupidon" to {_rolespossible::*}
		if {lg::config::angel::size} is not 0:
			loop {lg::config::angel::size} times:
				add "Ange" to {_rolespossible::*}
		if {lg::config::fox::size} is not 0:
			loop {lg::config::fox::size} times:
				add "Renard" to {_rolespossible::*}
		if {lg::config::werewolf::size} is not 0:
			loop {lg::config::werewolf::size} times:
				add "Loup-garou" to {_rolespossible::*}
		if {lg::config::Wwerewolf::size} is not 0:
			loop {lg::config::Wwerewolf::size} times:
				add "Loup-garou blanc" to {_rolespossible::*}
		if {lg::config::Owerewolf::size} is not 0:
			loop {lg::config::Owerewolf::size} times:
				add "Infect père des loups" to {_rolespossible::*}
		if {lg::config::killer::size} is not 0:
			loop {lg::config::killer::size} times:
				add "Assassin" to {_rolespossible::*}
		if {lg::config::wildchild::size} is not 0:
			loop {lg::config::wildchild::size} times:
				add "Enfant sauvage" to {_rolespossible::*}
		if {lg::config::thief::size} is not 0:
			loop {lg::config::thief::size} times:
				add "Voleur" to {_rolespossible::*}
		if {lg::config::Awerewolf::size} is not 0:
			loop {lg::config::Awerewolf::size} times:
				add "Loup-garou amnésique" to {_rolespossible::*}
		if {lg::config::savior::size} is not 0:
			loop {lg::config::savior::size} times:
				add "Salvateur" to {_rolespossible::*}
		if {lg::config::inquisitor::size} is not 0:
			loop {lg::config::inquisitor::size} times:
				add "Inquisiteur" to {_rolespossible::*}
		if {lg::config::oracle::size} is not 0:
			loop {lg::config::oracle::size} times:
				add "Oracle" to {_rolespossible::*}
		set {_nbrdef} to 0
		while {_nbrdef} is not equal to size of {lg::joueurs::*}:
			if {_rolespossible::*} is set:
				set {_r} to random object out of {_rolespossible::*}
				remove {_r} from {_rolespossible::*}
				delete {_ok}
				loop all players:
					if {_ok} is not set:
						if {lg::%loop-player%::role} is not set:
							set {lg::%loop-player%::role} to {_r}
							set {_ok} to true
							add 1 to {_nbrdef}
			else:
				if {lg::info::start} is true:
					message "&8&l[&6&lLoup-garou&8&l] &7Vous n'avez pas défini assez de rôles... un villageois va être rajouté à la partie." to all players
					add "Villageois" to {_rolespossible::*}
				else:
					stop
		if {_rolespossible::*} is set:
			message "&8&l[&6&lLoup-garou&8&l] &7Il y a trop de rôles défini, certains n'on pas pu être mis dans la partie." to all players
		set {_test} to lgu_wincheck()
		if {_test} is true:
			message "&8&l[&6&lLoup-garou&8&l] &cERREUR, veuillez modifier les rôles présents dans la partie." to all players
			lgu_endgame()
		else:
			lgu_event()
			lgu_timer()
	else:
		if {lg::config::werewolf::size} is not 0:
			set {_sizelg} to ceil(size of {lg::joueurs::*} / 5)
		else:
			set {_sizelg} to 0
		if {lg::config::witch::size} is not 0:
			add "Sorcière" to {_rolespossible::*}
		if {lg::config::hunter::size} is not 0:
			add "Chasseur" to {_rolespossible::*}
		if {lg::config::seer::size} is not 0:
			add "Voyante" to {_rolespossible::*}
		if {lg::config::girl::size} is not 0:
			add "Petite fille" to {_rolespossible::*}
		if {lg::config::oldone::size} is not 0:
			add "Ancien" to {_rolespossible::*}
		if {lg::config::cupidon::size} is not 0:
			add "Cupidon" to {_rolespossible::*}
		if {lg::config::angel::size} is not 0:
			add "Ange" to {_rolespossible::*}
		if {lg::config::fox::size} is not 0:
			add "Renard" to {_rolespossible::*}
		if {lg::config::Wwerewolf::size} is not 0:
			add "Loup-garou blanc" to {_rolespossible::*}
		if {lg::config::Owerewolf::size} is not 0:
			add "Infect père des loups" to {_rolespossible::*}
		if {lg::config::killer::size} is not 0:
			add "Assassin" to {_rolespossible::*}
		if {lg::config::wildchild::size} is not 0:
			add "Enfant sauvage" to {_rolespossible::*}
		if {lg::config::thief::size} is not 0:
			add "Voleur" to {_rolespossible::*}
		if {lg::config::Awerewolf::size} is not 0:
			add "Loup-garou amnésique" to {_rolespossible::*}
		if {lg::config::savior::size} is not 0:
			add "Salvateur" to {_rolespossible::*}
		if {lg::config::inquisitor::size} is not 0:
			add "Inquisiteur" to {_rolespossible::*}
		if {lg::config::oracle::size} is not 0:
			add "Oracle" to {_rolespossible::*}
		if {_sizelg} is not 0:
			loop {_sizelg} times:
				add "Loup-garou" to {_rolespossible2::*}
		while size of {_rolespossible2::*} is not equal to size of {lg::joueurs::*}:
			if {_rolespossible::*} is set:
				set {_r} to random object out of {_rolespossible::*}
				remove {_r} from {_rolespossible::*}
				add {_r} to {_rolespossible2::*}
			else:
				add "Villageois" to {_rolespossible2::*}

		loop {lg::joueurs::*}:
			set {_r} to random object out of {_rolespossible2::*}
			remove {_r} from {_rolespossible2::*}
			set {lg::%loop-value%::role} to {_r}
		set {_test} to lgu_wincheck()
		if {_test} is true:
			message "&8&l[&6&lLoup-garou&8&l] &cERREUR, veuillez modifier les rôles présents dans la partie." to all players
			lgu_endgame()
		else:
			lgu_event()
			lgu_timer()

function lgu_spec(p: player,page: number):
	set {_s} to 1
	set {_i} to 1
	loop {lg::spec::*}:
		if {_s} is 29:
			add 1 to {_i}
			set {_s} to 1
		add loop-value to {_player.%{_i}%::*}
		add 1 to {_s}
	open virtual chest inventory with size 6 with name "&8Liste des spectateurs" to {_p}
	make a gui slot 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 44, 45, 46, 48, 50, 52 and 53 of {_p} with 1 gray stained glass pane named "&f"
	if {_page} is not 1:
		make a gui slot 47 of {_p} with skull of ("MHF_ArrowLeft" parsed as an offline player) named "Page précédante" to run:
			set {_page2} to {_page} - 1
			lgu_spec({_p},{_page2})
	else:
		make a gui slot 47 of {_p} with 1 gray stained glass pane named "&f"
	set {_i2} to {_page} + 1
	if {_player.%{_i2}%::*} is set:
		make a gui slot 51 of {_p} with skull of ("MHF_ArrowRight" parsed as an offline player) named "Page suivante" to run:
			lgu_spec({_p},{_i2})
	else:
		make a gui slot 51 of {_p} with 1 gray stained glass pane named "&f"
	set {_s} to 10
	loop {_player.%{_page}%::*}:
		if {_s} is 16:
			set {_s} to 18
		else if {_s} is 25:
			set {_s} to 27
		else if {_s} is 34:
			set {_s} to 36
		else if {_s} is 43:
			set {_s} to 45
		set {_loopvalue} to loop-value
		make a gui slot {_s} of {_p} with skull of ("%loop-value%" parsed as an offline player) named "&6%loop-value%" with lore "" and "&8>> &aClique droit pour supprimer&l" to run:
			if clicked type is equal to right mouse button:
				message "&8&l[&6&lLoup-garou&8&l] &7Le joueur &3%{_loopvalue}% &7a été enlevé de la liste des spectateurs." to {_p}
				delete {lg::spec::%{_loopvalue}%}
				lgu_spec({_p},{_page})
	make a gui slot 49 of {_p} with 1 anvil named "&eAjouter un joueur" to run:
		close {_p}'s inventory
		message "&8&l[&6&lLoup-garou&8&l] &7Vous avez 30 seondes pour écrir dans le chat le nom du joueur à ajouter aux spectateurs. Ou tapez ""annuler"" dans le chat" to {_p}
		set {lg::%{_p}%::spec} to true
		set {_s} to 0
		while {_s} is not 30:
			if {lg::%{_p}%::spec} is not set:
				message "&8&l[&6&lLoup-garou&8&l] &7Vous avez bien annulé l'ajout d'un joueur aux spectateurs." to {_p}
				stop
			else if {lg::%{_p}%::spec} is false:
				delete {lg::%{_p}%::spec}
				stop
			wait 1 second
			add 1 to {_s}
		if {lg::%{_p}%::spec} is false:
			delete {lg::%{_p}%::spec}
			stop
		else if {lg::%{_p}%::spec} is not set:
			message "&8&l[&6&lLoup-garou&8&l] &7Vous avez bien annulé l'ajout d'un joueur aux spectateurs." to {_p}
			stop
		delete {lg::%{_p}%::spec}
		message "&8&l[&6&lLoup-garou&8&l] &7Vous n'avez ajouté aucun joueur aux spectateurs." to {_p}

function lgu_scoreboard():
	skellett delete stylish scoreboard named "LG_UHC"
	skellett create a new stylish scoreboard named "LG_UHC"
	set title of stylish scoreboard "LG_UHC" to "&e&lLg UHC"
	skellett create a new id based score "LG_UHC_10" with text "&c&lTEMPS:" slot 10 for stylish scoreboard "LG_UHC"
	skellett create a new id based score "LG_UHC_9" with text "&7Durée: &c00:00" slot 9 for stylish scoreboard "LG_UHC"
	skellett create a new id based score "LG_UHC_8" with text "&7Nuit suivante: &c00:00" slot 8 for stylish scoreboard "LG_UHC"
	skellett create a new id based score "LG_UHC_7" with text "&7Mur: &c00:00" slot 7 for stylish scoreboard "LG_UHC"
	skellett create a new id based score "LG_UHC_6" with text "&7Pvp: &c00:00" slot 6 for stylish scoreboard "LG_UHC"
	skellett create a new id based score "LG_UHC_5" with text "&7Révélation: &c00:00" slot 5 for stylish scoreboard "LG_UHC"
	skellett create a new id based score "LG_UHC_4" with text "&3&lJOUEURS: &3%size of {lg::joueurs::*}%" slot 4 for stylish scoreboard "LG_UHC"
	skellett create a new id based score "LG_UHC_3" with text "&a&lLocalisation" slot 3 for stylish scoreboard "LG_UHC"
	skellett create a new id based score "LG_UHC_2" with text "&7Bordure: &a+%{lg::config::dborder} / 2%&7/&a-%{lg::config::dborder} / 2%" slot 2 for stylish scoreboard "LG_UHC"
	loop all players:
		set stylish scoreboard of loop-player to "LG_UHC"
function lgu_event():
	if {lg::config::pvp} is equal to 0:
		message "" to all players
		message "&8&l[&6&lLoup-garou&8&l] &e&lLe pvp &7est activé." to all players
		message "" to all players
		set {lg::current::pvp} to true
		if {lg::config::finalheal} is true:
			loop {lg::joueurs::*}:
				set loop-value's health to loop-value's max health
		skellett delete id based score "LG_UHC_6" for stylish scoreboard with named "LG_UHC"
	if {lg::config::rtime} is equal to 0:
		set {lg::current::rev} to true
		loop {lg::joueurs::*}:
			lgu_rolesgive(loop-value,{lg::%loop-value%::role},true)
			if {lg::config::randomlover} is true:
				add loop-value to {_lv::*}
		set {_r} to random object out of {_lv::*}
		remove {_r} from {_lv::*}
		set {lg::amoureux::1} to {_r}
		set {_r} to random object out of {_lv::*}
		set {lg::amoureux::2} to {_r}
		loop {lg::amoureux::*}:
			message "&8&l>> &dAmoureux" to loop-value
			if loop-index is "1":
				message "&7Ta moitié est &d&l%{lg::amoureux::2}%&7. Si l'un de vous deux meurt l'autre également." to loop-value
			else:
				message "&7Ta moitié est &d&l%{lg::amoureux::1}%&7. Si l'un de vous deux meurt l'autre également." to loop-value
			message "&7Tu devrais retrouver ta moitié afin de pouvoir ""t'amuser"" avec elle." to loop-value
			message "&fDe plus, tu peux discuter avec ta moitié en mettant un ""!"" devant ton message." to loop-value
			message "" to loop-value
			message "&6Tu peux gagner ..." to loop-value
			message "&6... &favec le village si toi et ta moitié êtes du village." to loop-value
			message "&6... &favec les loups-garous si vous êtes tout les deux loups-garous." to loop-value
			message "&6... &fjuste avec ta moitié si seulement l'un de vous deux est un ennemi du village." to loop-value
			message "&6... &fjuste avec ta moitié si vous êtes tout deux différents ennemis du village." to loop-value
			message "&6Mais dans tout les cas avec Cupidon et ta moitié." to loop-value
			set {_l} to loop-value
			give 1 compass to {_l}
			set {_osef} to lgu_wincheck()
		skellett delete id based score "LG_UHC_5" for stylish scoreboard with named "LG_UHC"
	if {lg::config::tborder} is equal to 0:
		message "" to all players
		message "&8&l[&6&lLoup-garou&8&l] &a&lLa bordure &7commence à bouger." to all players
		message "" to all players
		skellett delete id based score "LG_UHC_7" for stylish scoreboard with named "LG_UHC"
		set {lg::current::border} to true
		set {_s} to 0
		set {_timespan} to "%({lg::config::dborder} - {lg::config::fborder})% seconds" parsed as timespans
		set diameter of world("%{lg::current::world}%") to {lg::config::fborder} over {_timespan}
		set {_blocks} to {lg::config::dborder} - {lg::config::fborder}
		loop {_blocks} times:
			add 1 to {_s}
			set {_calculb} to {lg::config::dborder} - {_s}
			set {_calculb} to {_calculb} / 2
			set {_calculb} to round({_calculb})
			set {lg::current::border} to {_calculb}
			set the text of id "LG_UHC_2" to "&7Bordure: &a+%{_calculb}%&7/&a-%{_calculb}%"
			wait 1 second
			if {lg::info::start} is not true:
				stop trigger

function lgu_eventmessage(t: text):
	if {_t} is equal to "pvp":
		if {lg::current::pvp} is not true:
			set {_s} to 5
			loop 5 times:
				message "&8&l[&6&lLoup-garou&8&l] &e&lLe pvp &7s'activera dans %{_s}% seconde(s)." to all players
				remove 1 from {_s}
				wait 1 second
			set {lg::current::pvp} to true
			if {lg::config::finalheal} is true:
				loop {lg::joueurs::*}:
					set loop-value's health to loop-value's max health
			message "" to all players
			message "&8&l[&6&lLoup-garou&8&l] &e&lLe pvp &7est activé." to all players
			message "" to all players
			skellett delete id based score "LG_UHC_6" for stylish scoreboard with named "LG_UHC"
	else if {_t} is equal to "border":
		if {lg::current::border} is not true:
			set {_s} to 5
			loop 5 times:
				message "&8&l[&6&lLoup-garou&8&l] &a&lLa bordure &7bougera dans %{_s}% seconde(s)." to all players
				remove 1 from {_s}
				wait 1 second
			message "" to all players
			message "&8&l[&6&lLoup-garou&8&l] &a&lLa bordure &7commence à bouger." to all players
			message "" to all players
			skellett delete id based score "LG_UHC_7" for stylish scoreboard with named "LG_UHC"
			set {lg::current::border} to true
			set {_s} to 0
			set {_timespan} to "%({lg::config::dborder} - {lg::config::fborder})% seconds" parsed as timespans
			set diameter of world("%{lg::current::world}%") to {lg::config::fborder} over {_timespan}
			set {_blocks} to {lg::config::dborder} - {lg::config::fborder}
			loop {_blocks} times:
				add 1 to {_s}
				set {_calculb} to {lg::config::dborder} - {_s}
				set {_calculb} to {_calculb} / 2
				set {_calculb} to round({_calculb})
				set {lg::current::border} to {_calculb}
				set the text of id "LG_UHC_2" to "&7Bordure: &a+%{_calculb}%&7/&a-%{_calculb}%"
				wait 1 second
				if {lg::info::start} is not true:
					stop trigger
	else if {_t} is equal to "roles":
		if {lg::current::rev} is not true:
			set {_s} to 5
			loop 5 times:
				message "&8&l[&6&lLoup-garou&8&l] &e&lLes rôles &7seront dévoilés dans %{_s}% seconde(s)." to all players
				remove 1 from {_s}
				wait 1 second
			set {lg::current::rev} to true
			skellett delete id based score "LG_UHC_5" for stylish scoreboard with named "LG_UHC"
			loop {lg::joueurs::*}:
				lgu_rolesgive(loop-value,{lg::%loop-value%::role},true)
				if {lg::config::randomlover} is true:
					add loop-value to {_lv::*}
			set {_r} to random object out of {_lv::*}
			remove {_r} from {_lv::*}
			set {lg::amoureux::1} to {_r}
			set {_r} to random object out of {_lv::*}
			set {lg::amoureux::2} to {_r}
			loop {lg::amoureux::*}:
				message "&8&l>> &dAmoureux" to loop-value
				if loop-index is "1":
					message "&7Ta moitié est &d&l%{lg::amoureux::2}%&7. Si l'un de vous deux meurt l'autre également." to loop-value
				else:
					message "&7Ta moitié est &d&l%{lg::amoureux::1}%&7. Si l'un de vous deux meurt l'autre également." to loop-value
				message "&7Tu devrais retrouver ta moitié afin de pouvoir ""t'amuser"" avec elle." to loop-value
				message "&fDe plus, tu peux discuter avec ta moitié en mettant un ""!"" devant ton message." to loop-value
				message "" to loop-value
				message "&6Tu peux gagner ..." to loop-value
				message "&6... &favec le village si toi et ta moitié êtes du village." to loop-value
				message "&6... &favec les loups-garous si vous êtes tout les deux loups-garous." to loop-value
				message "&6... &fjuste avec ta moitié si seulement l'un de vous deux est un ennemi du village." to loop-value
				message "&6... &fjuste avec ta moitié si vous êtes tout deux différents ennemis du village." to loop-value
				message "&6Mais dans tout les cas avec Cupidon et ta moitié." to loop-value
				set {_l} to loop-value
				give 1 compass to {_l}
				set {_osef} to lgu_wincheck()
function lgu_rolesgive(p: player,r: text,b: boolean):
	message "&2------------------------------------" to {_p}
	message "" to {_p}
	switch {_r}:
		case "Villageois":
			message "&8&l>> &2&lVillageois" to {_p}
			message "&7Il est avec le village." to {_p}
			message "&fIl n'a aucun pouvoir (mais bon il peut toujours jouer un rôle important)." to {_p}
			message "" to {_p}
			message "&6Il peut gagner ..." to {_p}
			message "&8&l>> &fsi les loups-garous et l'assassin sont morts." to {_p}
		case "Loup-garou amnésique":
			message "&8&l>> &2&lVillageois" to {_p}
			message "&7Il est avec le village." to {_p}
			message "&fIl n'a aucun pouvoir (mais bon il peut toujours jouer un rôle important)." to {_p}
			message "" to {_p}
			message "&6Il peut gagner ..." to {_p}
			message "&8&l>> &fsi les loups-garous et l'assassin sont morts." to {_p}
		case "Chasseur":
			message "&8&l>> &2&lChasseur" to {_p}
			message "&7Il est avec le village." to {_p}
			message "&fIl peut enlever la moitié de la vie d'un joueur à sa mort." to {_p}
			message "" to {_p}
			message "&6Il peut gagner ..." to {_p}
			message "&8&l>> &fsi les loups-garous et l'assassin sont morts." to {_p}
		case "Voyante":
			message "&8&l>> &2&lVoyante" to {_p}
			message "&7Elle est avec le village." to {_p}
			message "&fAu début de chaque jour, elle peut connaître le rôle d'un joueur." to {_p}
			message "" to {_p}
			message "&6Elle peut gagner ..." to {_p}
			message "&8&l>> &fsi les loups-garous et l'assassin sont morts." to {_p}
			message "" to {_p}
			if {lg::config::meetup} is false:
				message "&3Pour faire ceci, elle a le droit à :" to {_p}
				message "&a&l+ &r&84 &r&7blocs d'obsidienne" to {_p}
				message "&a&l+ &r&85 &r&7bibliothèques" to {_p}
			if {lg::%{_p}%::role} is "Voyante":
				if {_b} is true:
					if {lg::config::meetup} is false:
						give 4 obsidian to {_p}
						give 5 book shelf to {_p}

		case "Sorcière":
			message "&8&l>> &2&lSorcière" to {_p}
			message "&7Elle est avec le village." to {_p}
			message "&fElle peut ressuciter une seule personne (sauf elle même) juste après sa mort." to {_p}
			message "" to {_p}
			message "&6Elle peut gagner ..." to {_p}
			message "&8&l>> &fsi les loups-garous et l'assassin sont morts." to {_p}
			message "" to {_p}
			message "&3Pour faire ceci, elle a le droit à :" to {_p}
			message "&a&l+ &r&81 &r&7potion de régénération" to {_p}
			message "&a&l+ &r&81 &r&7potion de soint instantané" to {_p}
			message "&a&l+ &r&82 &r&7potion de dégâts instantanés" to {_p}
			if {lg::%{_p}%::role} is "Sorcière":
				if {_b} is true:
					give 1 splash potion of regeneration to {_p}
					give 1 splash potion of healing to {_p}
					give 2 splash potion of harming to {_p}
		case "Petite fille":
			message "&8&l>> &2&lPetite fille" to {_p}
			message "&7Elle est avec le village." to {_p}
			message "&fElle peut voir les messages des loups-garous la nuit." to {_p}
			message "" to {_p}
			message "&6Elle peut gagner ..." to {_p}
			message "&8&l>> &fsi les loups-garous et l'assassin sont morts." to {_p}
			message "" to {_p}
			message "&3Pour faire ceci, elle a le droit à :" to {_p}
			message "&a&l+ &r&7un effet d'invisibilité nocturne" to {_p}
			message "&a&l+ &r&7un effet de vision nocturne" to {_p}
		case "Ancien":
			message "&8&l>> &2&lAncien" to {_p}
			message "&7Il est avec le village.." to {_p}
			message "&fIl a deux vies (Hé non pas neuf)." to {_p}
			message "" to {_p}
			message "&6Il peut gagner ..." to {_p}
			message "&8&l>> &fsi les loups-garous et l'assassin sont morts." to {_p}
			message "" to {_p}
			message "&3Pour faire ceci, il a le droit à :" to {_p}
			message "&a&l+ &r&7un effet de résistance permanent" to {_p}
			if {lg::%{_p}%::role} is "Ancien":
				if {_b} is true:
					apply resistance without any particles to {_p} for 99999 days
		case "Cupidon":
			message "&8&l>> &2&lCupidon" to {_p}
			message "&7Il est avec le village." to {_p}
			message "&fIl peut unir deux joueurs à la vie à la mort." to {_p}
			message "" to {_p}
			message "&6Il peut gagner ..." to {_p}
			message "&8&l>> &fsi les loups-garous et l'assassin sont morts." to {_p}
			message "&8&l>> &favec le couple." to {_p}
			message "" to {_p}
			message "&3Pour faire ceci, il a le droit à :" to {_p}
			message "&a&l+ &r&81 &r&7livre enchanté frappe II" to {_p}
			message "&a&l+ &r&81 &r&7livre enchanté puissance II" to {_p}
			message "&a&l+ &r&864 &r&7flèches" to {_p}
			if {lg::config::meetup} is true:
				message "&a&l+&cMEETUP &r&81 &r&7Enclume endommagé" to {_p}
				message "&a&l+&cMEETUP &r&87 &r&7Bouteilles d'xp" to {_p}
			message "" to {_p}
			if {lg::%{_p}%::role} is "Cupidon":
				if {_b} is true:
					message "<tooltip:&cCette action n'est réalisable qu'une fois.><cmd:/lg power Cupidon>&8&l>> &d&lClique ici pour unir deux joueurs" to {_p}
					make console execute command "/minecraft:give %{_p}% enchanted_book 1 0 {StoredEnchantments:[{id:49,lvl:2}]}"
					make console execute command "/minecraft:give %{_p}% enchanted_book 1 0 {StoredEnchantments:[{id:48,lvl:2}]}"
					give 64 arrow to {_p}
					if {lg::config::meetup} is true:
						make console execute command "/minecraft:give %{_p}% anvil 1 2"
						give 7 experience bottle to {_p}

		case "Ange":
			message "&8&l>> &2&lAnge" to {_p}
			message "&7&7Il/Elle est avec le village." to {_p}
			message "&fLes votes ne l'affectent pas et il gagne un cœur toutes les deux personnes votant contre lui." to {_p}
			message "" to {_p}
			message "&6Il peut gagner ..." to {_p}
			message "&8&l>> &fsi les loups-garous et l'assassin sont morts." to {_p}
			message "" to {_p}
			message "&3Pour faire ceci, il a le droit à :" to {_p}
			message "&a&l+ &r&81 &r&7potion de regeneration" to {_p}
			if {lg::%{_p}%::role} is "Voyante":
				if {_b} is true:
					give 1 splash potion of regeneration to {_p}
		case "Renard":
			message "&8&l>> &2&lRenard" to {_p}
			message "&7Il est avec le village." to {_p}
			message "&fIl peut flairer trois fois durant la partie grâce à la commande /lg flairer. Celle-ci t'indiquera si un loup-garou se trouve dans un rayon de 50 blocs." to {_p}
			message "" to {_p}
			message "&6Il peut gagner ..." to {_p}
			message "&8&l>> &fsi les loups-garous et l'assassin sont morts." to {_p}
			message "" to {_p}
			message "&3Pour faire ceci, il a le droit à :" to {_p}
			message "&a&l+ &r&81 &r&7potion de soin instantané" to {_p}
			if {lg::%{_p}%::role} is "Renard":
				if {_b} is true:
					give 1 splash potion of healing to {_p}
		case "Loup-garou":
			message "&8&l>> &2&lLoup-garou" to {_p}
			message "&fIl est un ennemi du village." to {_p}
			message "&fIl peut parler aux autres loups-garous durant la nuit en mettant un ""&c*&f"" devant son message." to {_p}
			message "&fIl peut voir la liste des autres loups-garous en faisant /lg lg" to {_p}
			message "" to {_p}
			message "&6Tu peux gagner ..." to {_p}
			message "&8&l>> &fsi les villageois, le loup-garou blanc et l'assassin sont morts." to {_p}
			message "" to {_p}
			message "&3Pour faire ceci, tu as le droit à :" to {_p}
			message "&a&l+ &r&7un effet de force nocturne" to {_p}
			message "&a&l+ &r&7un effet de vision nocturne" to {_p}
			if {lg::%{_p}%::role} is "Loup-garou" or "Loup-garou blanc" or "Infect père des loups":
				loop {lg::joueurs::*}:
					if {lg::%loop-value%::role} is "Loup-garou" or "Loup-garou blanc" or "Infect père des loups":
						add loop-value to {_lg::*}
				set {_lg} to "%{_lg::*}%"
				replace all "and" in {_lg} with "et"
				message "&8&l[&cLOUP-GAROU&8&l] &c%{_lg}%" to {_p}
		case "Infect père des loups":
			message "&8&l>> &2&lInfect père des loups" to {_p}
			message "&7Il est un ennemi du village." to {_p}
			message "&fIl peut parler aux autres loups-garous durant la nuit en mettant un ""&c*&f"" devant son message." to {_p}
			message "&fIl peut ressuciter un joueur qui se joindra aux loups-garous juste après sa mort." to {_p}
			message "&fIl peut voir la liste des autres loups-garous en faisant /lg lg" to {_p}
			message "" to {_p}
			message "&6Il peut gagner ..." to {_p}
			message "&8&l>> &fsi les villageois, le loup-garou blanc et l'assassin sont morts." to {_p}
			message "" to {_p}
			message "&3Pour faire ceci, il a le droit à :" to {_p}
			message "&a&l+ &r&7un effet de force nocturne" to {_p}
			message "&a&l+ &r&7un effet de vision nocturne" to {_p}
			if {lg::%{_p}%::role} is "Loup-garou" or "Loup-garou blanc" or "Infect père des loups":
				loop {lg::joueurs::*}:
					if {lg::%loop-value%::role} is "Loup-garou" or "Loup-garou blanc" or "Infect père des loups":
						add loop-value to {_lg::*}
				set {_lg} to "%{_lg::*}%"
				replace all "and" in {_lg} with "et"
				message "&8&l[&cLOUP-GAROU&8&l] &c%{_lg}%" to {_p}
		case "Loup-garou blanc":
			message "&8&l>> &2&lLoup-garou blanc" to {_p}
			message "&7Il est l'ennemi de tout le monde. Il doit se faire passer pour un loup-garou" to {_p}
			message "&fIl peut parler aux autres loups-garous durant la nuit en mettant un ""&c*&f"" devant son message." to {_p}
			message "&fIl peut voir la liste des autres loups-garous en faisant /lg lg" to {_p}
			message "" to {_p}
			message "&6Il peut gagner ..." to {_p}
			message "&8&l>> &fsi il est le dernier survivant." to {_p}
			message "" to {_p}
			message "&3Pour faire ceci, il a le droit à :" to {_p}
			message "&a&l+ &r&7un effet de force nocturne" to {_p}
			message "&a&l+ &r&7un effet de vision nocturne" to {_p}
			if {lg::%{_p}%::role} is "Loup-garou" or "Loup-garou blanc" or "Infect père des loups":
				loop {lg::joueurs::*}:
					if {lg::%loop-value%::role} is "Loup-garou" or "Loup-garou blanc" or "Infect père des loups":
						add loop-value to {_lg::*}
				set {_lg} to "%{_lg::*}%"
				replace all "and" in {_lg} with "et"
				message "&8&l[&cLOUP-GAROU&8&l] &c%{_lg}%" to {_p}
				if {_b} is true:
					if {lg::%{_p}%::role} is "Loup-garou blanc":
						set {_p}'s max health to 12
		case "Assassin":
			message "&8&l>> &2&lAssassin" to {_p}
			message "&7Il est l'ennemi de tout le monde. Il doit se faire passer pour un membre du camp des villageois." to {_p}
			message "&fIl n'a aucun pouvoir." to {_p}
			message "" to {_p}
			message "&6Il peut gagner ..." to {_p}
			message "&8&l>> &fsi il est le dernier survivant." to {_p}
			message "" to {_p}
			message "&3Pour faire ceci, il a le droit à :" to {_p}
			message "&a&l+ &r&81 &r&7livre enchanté tranchant III" to {_p}
			message "&a&l+ &r&81 &r&7livre enchanté protection II" to {_p}
			message "&a&l+ &r&81 &r&7livre enchanté puissance I" to {_p}
			message "&a&l+ &r&7un effet de force le jour" to {_p}
			if {lg::config::meetup} is true:
				message "&a&l+&cMEETUP &r&81 &r&7Enclume endommagé" to {_p}
				message "&a&l+&cMEETUP &r&810 &r&7Bouteilles d'xp" to {_p}
			message "" to {_p}
			if {lg::%{_p}%::role} is "Assassin":
				if {_b} is true:
					make console execute command "/minecraft:give %{_p}% enchanted_book 1 0 {StoredEnchantments:[{id:16,lvl:3}]}"
					make console execute command "/minecraft:give %{_p}% enchanted_book 1 0 {StoredEnchantments:[{id:0,lvl:2}]}"
					make console execute command "/minecraft:give %{_p}% enchanted_book 1 0 {StoredEnchantments:[{id:48,lvl:1}]}"
					if {lg::config::meetup} is true:
						make console execute command "/minecraft:give %{_p}% anvil 1 2"
						give 10 experience bottle to {_p}

		case "Enfant sauvage":
			message "&8&l>> &2&lEnfant sauvage" to {_p}
			message "&7Il est avec le village si son maître est vivant." to {_p}
			message "&fIl chosit son maître lors de la révélation des rôles, si celui-ci meurt il devient loup-garou." to {_p}
			message "" to {_p}
			message "&6Il peut gagner ..." to {_p}
			message "&8&l>> &favec le village si son maître est vivant." to {_p}
			message "&8&l>> &favec les loups-garous si son maître meurt." to {_p}
			message "" to {_p}
			if {lg::%{_p}%::role} is "Enfant sauvage":
				if {_b} is true:
					message "<tooltip:&cCette action n'est réalisable qu'une fois.><cmd:/lg power wildchild>&8&l>> &2&lClique ici pour désigner ton maître." to {_p}
		case "Voleur":
			message "&8&l>> &2&lVoleur" to {_p}
			message "&7Il est avec le village." to {_p}
			message "&fIl peut voler le rôle d'un joueur à la mort d'un joueur qu'il tue et utiliser ses pouvoirs par la suite." to {_p}
			message "" to {_p}
			message "&6Il peut gagner ..." to {_p}
			message "&8&l>> &fsi les loups-garous et l'assassin sont morts." to {_p}
			if {lg::%{_p}%::role} is "Voleur":
				if {_b} is true:
					set {lg::%{_p}%::voleur} to true
		case "Salvateur":
			message "&8&l>> &2&lSalvateur" to {_p}
			message "&7Il est avec le village." to {_p}
			message "&fIl peut donner resistance resistance I à un joueur de son choix pour une journée chaque jour." to {_p}
			message "" to {_p}
			message "&6Il peut gagner ..." to {_p}
			message "&8&l>> &fsi les loups-garous et l'assassin sont morts." to {_p}
		case "Oracle":
			message "&8&l>> &2&lOracle" to {_p}
			message "&7Elle est avec le village." to {_p}
			message "&fAu début de chaque jour, elle peut savoir si deux joueurs de son choix (sauf elle-même) sont du même camp ou sont ennemis." to {_p}
			message "" to {_p}
			message "&6Elle peux gagner ..." to {_p}
			message "&8&l>> &fsi les loups-garous et l'assassin sont morts." to {_p}
			message "&3Pour faire ceci, elle a le droit à :" to {_p}
			message "&a&l+ &r&83 &r&7Ender pearl" to {_p}
			if {lg::%{_p}%::role} is "Oracle":
				if {_b} is true:
					give 3 ender pearl to {_p}
		case "Inquisiteur":
			message "&8&l>> &2&lInquisiteur" to {_p}
			message "&fLes votes ne l'affectent pas et il gagne un cœur toutes les deux personnes votant contre lui." to {_p}
			message "&fLors de sa mort, le rôle du tueur est dévoilé." to {_p}
			message "" to {_p}
			message "&6Il peut gagner ..." to {_p}
			message "&8&l>> &fsi les loups-garous et l'assassin sont morts." to {_p}
	message "" to {_p}
	message "&2------------------------------------" to {_p}

function lgu_wincheck() :: boolean:
	loop {lg::joueurs::*}:
		if {lg::%loop-value%::role} is "Villageois" or "Chasseur" or "Voyante" or "Sorcière" or "Petite fille" or "Ancien" or "Cupidon" or "Ange" or "Renard" or "Enfant sauvage" or "Loup-garou amnésique" or "Voleur" or "Salvateur" or "Inquisiteur" or "Oracle":
			set {_v} to true
		else if {lg::%loop-value%::role} is "Loup-garou" or "Infect père des loups":
			set {_lg} to true
		else if {lg::%loop-value%::role} is "Assassin" or "Loup-garou blanc":
			set {_solo} to true
		if loop-value is {lg::amoureux::1}:
			set {_s} to 1
			if {_oklover} is not set:
				set {_oklover} to true
				loop {lg::amoureux::*}:
					if {lg::%loop-value-2%::role} is "Assassin" or "Loup-garou blanc":
						set {_lover} to "solo"
					else if {lg::%loop-value-2%::role} is "Villageois" or "Chasseur" or "Voyante" or "Sorcière" or "Petite fille" or "Ancien" or "Cupidon" or "Ange" or "Renard" or "Enfant sauvage" or "Loup-garou amnésique" or "Voleur" or "Salvateur" or "Inquisiteur" or "Oracle":
						set {_love.%{_s}%} to "v"
					else if {lg::%loop-value-2%::role} is "Loup-garou" or "Infect père des loups":
						set {_love.%{_s}%} to "lg"
					add 1 to {_s}
		add loop-value to {_alive::*}
	if {_oklover} is set:
		if {_lover} is not "solo":
			if {_love.1} is not {_love.2}:
				set {_lover} to "solo"
			else:
				if {_love.1} is "v":
					set {_lover} to "v"
				else:
					set {_lover} to "lg"
					set {_lg} to true
	set {_alive} to "%{_alive::*}%"
	replace all "and" in {_alive} with "et"
	if {_lover} is not "solo":
		if {_solo} is not set:
			if {_v} is true:
				if {_lg} is not set:
					message "&a------------------------------------" to all players
					message "" to all players
					message "&8&l>> &aLes villageois ont gagnés !!!" to all players
					message "&7Bravo à %{_alive}% pour leur victoire ! ^^" to all players
					loop {lg::joueurs::*}:
						if {lg::%loop-value%::role} is "Loup-garou amnésique":
							message "&7Tu as gagné alors que tu étais Loup-garou amnésique, tu feras payer ces humains." to loop-value
					message "" to all players
					message "&a------------------------------------" to all players
					lgu_endgame()
					return true

			else:
				if {_lg} is set:
					if {_love.1} is not "v":
						message "&a------------------------------------" to all players
						message "" to all players
						message "&8&l>> &cLes loups-garous ont gagnés !!!" to all players
						message "&7Bravo à %{_alive}% pour leur victoire ! ^^" to all players
						message "" to all players
						message "&a------------------------------------" to all players
						lgu_endgame()
						return true
				else:
					message "&a------------------------------------" to all players
					message "" to all players
					message "&8&l>> &dLes amoureux ont gagnés !!!" to all players
					message "&7Bravo à %{_alive}% pour leur victoire ! ^^" to all players
					message "" to all players
					message "&a------------------------------------" to all players
					lgu_endgame()
					return true
		else:
			if size of {_alive::*} is 1:
				loop {_alive::*}:
					message "&a------------------------------------" to all players
					message "" to all players
					message "&8&l>> &7Bravo à %loop-value% pour sa victoire, il était %{lg::%loop-value%::role}% ! ^^" to all players
					message "" to all players
					message "&a------------------------------------" to all players
					lgu_endgame()
					return true

	else:
		loop {_alive::*}:
			if loop-value is not {lg::amoureux::1} or {lg::amoureux::2}:
				if {lg::%loop-value%::role} is not "Cupidon":
					set {_vic} to false
		if {_vic} is not false:
			message "&a------------------------------------" to all players
			message "" to all players
			message "&8&l>> &dLes amoureux ont gagnés !!!" to all players
			message "&7Bravo à %{_alive}% pour leur victoire ! ^^" to all players
			message "" to all players
			message "&a------------------------------------" to all players
			lgu_endgame()
			return true
	return false
function lgu_endgame():
	set {lg::info::start} to false
	loop all players:
		if {lg::%loop-player%::*} is set:
			delete {lg::%loop-player%::*}
		if {lg::joueurs::%loop-player%}:
			delete {lg::joueurs::%loop-player%}
			lgu_firework(location of loop-player)
		reset stylish scoreboard of loop-player
	delete {lg::amoureux::*}
	reset world("%{lg::current::world}%")
	delete {lg::current::*}
	loop 10 times:
		skellett delete id based score "LG_UHC_%loop-number%" for stylish scoreboard with named "LG_UHC"

	skellett delete stylish scoreboard named "LG_UHC"
	delete {lg::spec::*}
function lgu_firework(l: location):
	wait 1 seconds
	#launch trailing ball large coloured red, blue and green at {_l} timed 1
	#wait 1 seconds
	#launch flickering trailing creeper coloured green fading to red, black and green at {_l} timed 1
	#wait 1 seconds
	#launch trailing ball large coloured green, yellow and blue at {_l} timed 1
	#wait 1.5 seconds
	#launch flickering trailing creeper coloured red fading to red and green at {_l} timed 1
	#wait 1 seconds
	#launch trailing ball large coloured red, blue and green at {_l} timed 1

function lgu_respawn(p: player,p2: player):
	open virtual chest inventory with size 5 with name "&lChoisir le rôle" to {_p}
	make a gui slot 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43 and 44 of {_p} with 1 gray stained glass pane named "&f"
	set {_s} to 10
	loop 17 times:
		if {_s} is 17:
			set {_s} to 19
		if {_s} is 26:
			set {_s} to 28
		if {_s} is 10:
			set {_item} to "1 chest"
			set {_displayname} to "Villageois"
		else if {_s} is 11:
			set {_item} to "1 iron sword"
			set {_displayname} to "Chasseur"
		else if {_s} is 12:
			set {_item} to "1 potion of healing"
			set {_displayname} to "Sorcière"
		else if {_s} is 13:
			set {_item} to "1 magma cream"
			set {_displayname} to "Voyante"
		else if {_s} is 14:
			set {_item} to "1 eye of ender"
			set {_displayname} to "Petite fille"
		else if {_s} is 15:
			set {_item} to "1 oak sapling"
			set {_displayname} to "Ancien"
		else if {_s} is 16:
			set {_item} to "1 red wool"
			set {_displayname} to "Cupidon"
		else if {_s} is 19:
			set {_item} to "1 feather"
			set {_displayname} to "Ange"
		else if {_s} is 20:
			set {_item} to "1 name tag"
			set {_displayname} to "Renard"
		else if {_s} is 21:
			set {_item} to "1 rotten flesh"
			set {_displayname} to "Loup-garou"
		else if {_s} is 22:
			set {_item} to "1 white dye"
			set {_displayname} to "Loup-garou blanc"
		else if {_s} is 23:
			set {_item} to "1 coal"
			set {_displayname} to "Infect père des loups"
		else if {_s} is 24:
			set {_item} to "1 enchanted book"
			set {_displayname} to "Assassin"
		else if {_s} is 25:
			set {_item} to "1 vine"
			set {_displayname} to "Enfant sauvage"
		else if {_s} is 28:
			set {_displayname} to "Voleur"
			set {_item} to "1 clock"
		else if {_s} is 29:
			set {_displayname} to "Loup-garou amnésique"
			set {_item} to "1 paper"
		else if {_s} is 30:
			set {_displayname} to "Salvateur"
			set {_item} to "1 golden apple"
		if {_s} is not 16:
			add {_displayname} to {_rolerandom::*}
			make a gui slot {_s} of {_p} with ({_item}  parsed as item) named "&e%{_displayname}%" with lore "&7Cliquez pour définir " and "&7le rôle de %{_p2}%." to run:
				set {lg::%{_p2}%::role} to {_displayname}
				close {_p}'s inventory
				set {_p2}'s gamemode to survival
				apply resistance 4 without any particles to {_p2} for 30 seconds
				lgu_rolesgive({_p2},{lg::%{_p2}%::role},true)
				clear {_p2}' inventory
				if {lg::spec::%{_p2}%} is set:
					delete {lg::spec::%{_p2}%}
				if {lg::joueurs::%{_p2}%} is not set:
					set {lg::joueurs::%{_p2}%} to {_p2}

				if {lg::%{_p2}%::ADloc} is not set:
					if {lg::items::*} is set:
						set {_s} to 0
						loop {lg::items::items::*}:
							set slot {_s} of {_p2}'s inventory to loop-value-2
							add 1 to {_s}
						set {_p2}'s helmet to {lg::items::helmet}
						set {_p2}'s chestplate to {lg::items::chestplate}
						set {_p2}'s leggings to {lg::items::leggings}
						set {_p2}'s boots to {lg::items::boots}
						lgu_tp({_p2},true)
				else:
					add {lg::%{_p2}%::ADstuff::*} to {_p2}'s inventory
					teleport {_p2} to {lg::%{_p2}%::ADloc}

				message "" to all players
				message "&8&l[&6&lLoup-garou&8&l] &7Le joueur &3%{_p2}% &7rejoint la partie." to all players
				message "" to all players
				if {_displayname} is "Loup-garou" or "Infect père des loups" or "Loup-garou blanc":
					loop {lg::joueurs::*}:
						if {lg::%loop-value-2%::role} is "Loup-garou" or "Infect père des loups" or "Loup-garou blanc":
							message "&8&l[&c&lLG&8&l] &7Le joueur &3%{_p2}% &7est devenu &cloup-garou&7." to loop-value-2

		add 1 to {_s}
		make a gui slot 35 of {_p} with compass named "&eRôle aléatoire" with lore "&7Choisis un rôle aléatoire pour" and "&7%{_p2}%." to run:
			set {_r} to random object out of {_rolerandom::*}
			set {lg::%{_p2}%::role} to {_r}
			close {_p}'s inventory
			set {_p2}'s gamemode to survival
			apply resistance 4 without any particles to {_p2} for 30 seconds
			lgu_rolesgive({_p2},{_r},true)
			clear {_p2}' inventory
			if {lg::spec::%{_p2}%} is set:
				delete {lg::spec::%{_p2}%}
			if {lg::joueurs::%{_p2}%} is not set:
				set {lg::joueurs::%{_p2}%} to {_p2}

			if {lg::%{_p2}%::ADloc} is not set:
				if {lg::items::*} is set:
					set {_s} to 0
					loop {lg::items::items::*}:
						set slot {_s} of {_p2}'s inventory to loop-value-2
						add 1 to {_s}
					set {_p2}'s helmet to {lg::items::helmet}
					set {_p2}'s chestplate to {lg::items::chestplate}
					set {_p2}'s leggings to {lg::items::leggings}
					set {_p2}'s boots to {lg::items::boots}
					lgu_tp({_p2},true)
			else:
				add {lg::%{_p2}%::ADstuff::*} to {_p2}'s inventory
				teleport {_p2} to {lg::%{_p2}%::ADloc}

			message "" to all players
			message "&8&l[&6&lLoup-garou&8&l] &7Le joueur &3%{_p2}% &7rejoint la partie." to all players
			message "" to all players
			if {_r} is "Loup-garou" or "Infect père des loups" or "Loup-garou blanc":
				loop {lg::joueurs::*}:
					if {lg::%loop-value-2%::role} is "Loup-garou" or "Infect père des loups" or "Loup-garou blanc":
						message "&8&l[&c&lLG&8&l] &7Le joueur &3%{_p2}% &7est devenu &cloup-garou&7." to loop-value-2

			make a gui slot 16 of {_p} with 1 red wool named "&6Cupidon: &cRespawn impossible"
function lgu_cupidon(p: player,page: number,b: boolean):
	set {_s} to 1
	set {_i} to 1
	if {_b} is false:
		loop {lg::joueurs::*}:
			if {_s} is 29:
				add 1 to {_i}
				set {_s} to 1
			if loop-value's gamemode is not spectator:
				add loop-value to {_player.%{_i}%::*}
			add 1 to {_s}
	else:
		loop {lg::joueurs::*}:
			if loop-value is not {lg::amoureux::1}:
				if {_s} is 29:
					add 1 to {_i}
					set {_s} to 1
				add loop-value to {_player.%{_i}%::*}
			add 1 to {_s}
	if {_b} is false:
		open virtual chest inventory with size 6 with name "&dChoisissez le premier amoureux" to {_p}
	else:
		open virtual chest inventory with size 6 with name "&dChoisissez le second amoureux" to {_p}
	make a gui slot 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 44, 45, 46, 48, 49, 50, 52 and 53 of {_p} with 1 gray stained glass pane named "&f"
	if {_page} is not 1:
		make a gui slot 47 of {_p} with skull of ("MHF_ArrowLeft" parsed as an offline player) named "Page précédante" to run:
			set {_page2} to {_page} - 1
			lgu_cupidon({_p},{_page2},{_b})
	else:
		make a gui slot 47 of {_p} with 1 gray stained glass pane named "&f"
	set {_i2} to {_page} + 1
	if {_player.%{_i2}%::*} is set:
		make a gui slot 51 of {_p} with skull of ("MHF_ArrowRight" parsed as an offline player) named "Page suivante" to run:
			lgu_cupidon({_p},{_i2},{_b})
	else:
		make a gui slot 51 of {_p} with 1 gray stained glass pane named "&f"
	set {_s} to 10
	loop {_player.%{_page}%::*}:
		if {_s} is 17:
			set {_s} to 19
		else if {_s} is 26:
			set {_s} to 28
		else if {_s} is 35:
			set {_s} to 37
		else if {_s} is 44:
			set {_s} to 46
		set {_loopvalue} to loop-value
		make a gui slot {_s} of {_p} with skull of ("%loop-value%" parsed as an offline player) named "&d%loop-value%" to run:
			if {_b} is false:
				set {lg::amoureux::1} to {_loopvalue}
				lgu_cupidon({_p},1,true)
			else:
				set {lg::amoureux::2} to {_loopvalue}
				close {_p}'s inventory
				message ""
				message "&8&l[&dVous avez rendu les joueurs &3%{lg::amoureux::1}% &det &3%{lg::amoureux::2}% &damoureux&8&l]" to {_p}
				message ""
				set {lg::power::%{_p}%} to true
				loop {lg::amoureux::*}:
					message "&8&l>> &dAmoureux" to loop-value-2
					if loop-index-2 is "1":
						message "&7Ta moitié est &d&l%{lg::amoureux::1}%&7. Si l'un de vous deux meurt l'autre également." to loop-value-2
					else:
						message "&7Ta moitié est &d&l%{lg::amoureux::1}%&7. Si l'un de vous deux meurt l'autre également." to loop-value-2
					message "&7Tu devrais retrouver ta moitié afin de pouvoir ""t'amuser"" avec elle." to loop-value-2
					message "&fDe plus, tu peux discuter avec ta moitié en mettant un ""!"" devant ton message." to loop-value-2
					message "" to loop-value-2
					message "&6Tu peux gagner ..." to loop-value-2
					message "&6... &favec le village si toi et ta moitié êtes du village." to loop-value-2
					message "&6... &favec les loups-garous si vous êtes tout les deux loups-garous." to loop-value-2
					message "&6... &fjuste avec ta moitié si seulement l'un de vous deux est un ennemi du village." to loop-value-2
					message "&6... &fjuste avec ta moitié si vous êtes tout deux différents ennemis du village." to loop-value-2
					message "&6Mais dans tout les cas avec Cupidon et ta moitié." to loop-value-2
					set {_l} to loop-value-2
					give 1 compass to {_l}
				set {_osef} to lgu_wincheck()
		add 1 to {_s}
function lgu_vote(p: player,page: number):
	set {_s} to 1
	set {_i} to 1
	loop {lg::joueurs::*}:
		if {_s} is 29:
			add 1 to {_i}
			set {_s} to 1
		if loop-value's gamemode is not spectator:
			add loop-value to {_player.%{_i}%::*}
			add 1 to {_s}
	open virtual chest inventory with size 6 with name "&8Votez pour un joueur" to {_p}
	make a gui slot 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 44, 45, 46, 48, 49, 50, 52 and 53 of {_p} with 1 gray stained glass pane named "&f"
	if {_page} is not 1:
		make a gui slot 47 of {_p} with skull of ("MHF_ArrowLeft" parsed as an offline player) named "Page précédante" to run:
			set {_page2} to {_page} - 1
			lgu_vote({_p},{_page2})
	else:
		make a gui slot 47 of {_p} with 1 gray stained glass pane named "&f"
	set {_i2} to {_page} + 1
	if {_player.%{_i2}%::*} is set:
		make a gui slot 51 of {_p} with skull of ("MHF_ArrowRight" parsed as an offline player) named "Page suivante" to run:
			lgu_vote({_p},{_i2})
	else:
		make a gui slot 51 of {_p} with 1 gray stained glass pane named "&f"
	set {_s} to 10
	loop {_player.%{_page}%::*}:
		if {_s} is 17:
			set {_s} to 19
		else if {_s} is 26:
			set {_s} to 27
		else if {_s} is 35:
			set {_s} to 37
		else if {_s} is 44:
			set {_s} to 46
		set {_loopvalue} to loop-value
		if {lg::vote::%loop-value%} is not set:
			make a gui slot {_s} of {_p} with skull of ("%loop-value%" parsed as an offline player) named "&a%loop-value%" with lore "&eVotes contre: &l0" to run:
				if {lg::%player%::vote} is set:
					remove 1 from {lg::vote::%{lg::%player%::vote}%}
					if {lg::vote::%{lg::%player%::vote}%} is 0:
						delete {lg::vote::%{lg::%player%::vote}%}
				set {lg::%player%::vote} to {_loopvalue}
				if {lg::vote::%{_loopvalue}%} is not set:
					set {lg::vote::%{_loopvalue}%} to 1
				else:
					add 1 to {lg::vote::%{_loopvalue}%}
				close {_p}'s inventory
		else:
			make a gui slot {_s} of {_p} with skull of ("%loop-value%" parsed as an offline player) named "&a%loop-value%" with lore "&eVotes contre: &l%{lg::vote::%{_loopvalue}%}%" to run:
				if {lg::%player%::vote} is set:
					remove 1 from {lg::vote::%{lg::%player%::vote}%}
					if {lg::vote::%{lg::%player%::vote}%} is 0:
						delete {lg::vote::%{lg::%player%::vote}%}
				set {lg::%player%::vote} to {_loopvalue}
				if {lg::vote::%{_loopvalue}%} is not set:
					set {lg::vote::%{_loopvalue}%} to 1
				else:
					add 1 to {lg::vote::%{_loopvalue}%}
				close {_p}'s inventory
		add 1 to {_s}
function lgu_hunter(p: player,page: number):
	set {_s} to 1
	set {_i} to 1
	loop {lg::joueurs::*}:
		if {_s} is 29:
			add 1 to {_i}
			set {_s} to 1
		if loop-value's gamemode is not spectator:
			add loop-value to {_player.%{_i}%::*}
			add 1 to {_s}
	open virtual chest inventory with size 6 with name "&8Chassez un joueur" to {_p}
	make a gui slot 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 44, 45, 46, 48, 49, 50, 52 and 53 of {_p} with 1 gray stained glass pane named "&f"
	if {_page} is not 1:
		make a gui slot 47 of {_p} with skull of ("MHF_ArrowLeft" parsed as an offline player) named "Page précédante" to run:
			set {_page2} to {_page} - 1
			lgu_hunter({_p},{_page2})
	else:
		make a gui slot 47 of {_p} with 1 gray stained glass pane named "&f"
	set {_i2} to {_page} + 1
	if {_player.%{_i2}%::*} is set:
		make a gui slot 51 of {_p} with skull of ("MHF_ArrowRight" parsed as an offline player) named "Page suivante" to run:
			lgu_hunter({_p},{_i2})
	else:
		make a gui slot 51 of {_p} with 1 gray stained glass pane named "&f"
	set {_s} to 10
	loop {_player.%{_page}%::*}:
		if {_s} is 17:
			set {_s} to 19
		else if {_s} is 26:
			set {_s} to 28
		else if {_s} is 35:
			set {_s} to 37
		else if {_s} is 44:
			set {_s} to 46
		set {_loopvalue} to loop-value
		make a gui slot {_s} of {_p} with skull of ("%loop-value%" parsed as an offline player) named "&a%loop-value%"
		add 1 to {_s}
function lgu_inquisitor(p: player,page: number):
	set {_s} to 1
	set {_i} to 1
	loop {lg::joueurs::*}:
		if {_s} is 29:
			add 1 to {_i}
			set {_s} to 1
		if loop-value's gamemode is not spectator:
			add loop-value to {_player.%{_i}%::*}
			add 1 to {_s}
	open virtual chest inventory with size 6 with name "&8Punir un hérétique" to {_p}
	make a gui slot 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 44, 45, 46, 48, 49, 50, 52 and 53 of {_p} with 1 gray stained glass pane named "&f"
	if {_page} is not 1:
		make a gui slot 47 of {_p} with skull of ("MHF_ArrowLeft" parsed as an offline player) named "Page précédante" to run:
			set {_page2} to {_page} - 1
			lgu_hunter({_p},{_page2})
	else:
		make a gui slot 47 of {_p} with 1 gray stained glass pane named "&f"
	set {_i2} to {_page} + 1
	if {_player.%{_i2}%::*} is set:
		make a gui slot 51 of {_p} with skull of ("MHF_ArrowRight" parsed as an offline player) named "Page suivante" to run:
			lgu_hunter({_p},{_i2})
	else:
		make a gui slot 51 of {_p} with 1 gray stained glass pane named "&f"
	set {_s} to 10
	loop {_player.%{_page}%::*}:
		if {_s} is 17:
			set {_s} to 19
		else if {_s} is 26:
			set {_s} to 28
		else if {_s} is 35:
			set {_s} to 37
		else if {_s} is 44:
			set {_s} to 46
		set {_loopvalue} to loop-value
		make a gui slot {_s} of {_p} with skull of ("%loop-value%" parsed as an offline player) named "&a%loop-value%"
		add 1 to {_s}
function lgu_voyante(p: player,page: number):
	set {_s} to 1
	set {_i} to 1
	loop {lg::joueurs::*}:
		if loop-value is not {_p}:
			if {_s} is 29:
				add 1 to {_i}
				set {_s} to 1
			if loop-value's gamemode is not spectator:
				add loop-value to {_player.%{_i}%::*}
				add 1 to {_s}
	open virtual chest inventory with size 6 with name "&8Regardez un joueur" to {_p}
	make a gui slot 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 44, 45, 46, 48, 49, 50, 52 and 53 of {_p} with 1 gray stained glass pane named "&f"
	if {_page} is not 1:
		make a gui slot 47 of {_p} with skull of ("MHF_ArrowLeft" parsed as an offline player) named "Page précédante" to run:
			set {_page2} to {_page} - 1
			lgu_voyante({_p},{_page2})
	else:
		make a gui slot 47 of {_p} with 1 gray stained glass pane named "&f"
	set {_i2} to {_page} + 1
	if {_player.%{_i2}%::*} is set:
		make a gui slot 51 of {_p} with skull of ("MHF_ArrowRight" parsed as an offline player) named "Page suivante" to run:
			lgu_voyante({_p},{_i2})
	else:
		make a gui slot 51 of {_p} with 1 gray stained glass pane named "&f"
	set {_s} to 10
	loop {_player.%{_page}%::*}:
		if {_s} is 17:
			set {_s} to 19
		else if {_s} is 26:
			set {_s} to 28
		else if {_s} is 35:
			set {_s} to 37
		else if {_s} is 44:
			set {_s} to 46
		set {_loopvalue} to loop-value
		make a gui slot {_s} of {_p} with skull of ("%loop-value%" parsed as an offline player) named "&5%loop-value%" to run:
			close {_p}'s inventory
			if {lg::%{_loopvalue}%::role} is not "Loup-garou amnésique":
				message "&8&l[&5Le joueur &3%{_loopvalue}% &5est &e%{lg::%{_loopvalue}%::role}%&5.&8&l]" to {_p}
			else:
				message "&8&l[&5Le joueur &3%{_loopvalue}% &5est &eVillageois&5.&8&l]" to {_p}
			set {lg::power::%{_p}%} to true
		add 1 to {_s}
function lgu_oracle(p: player,page: number,b: text):
	set {_s} to 1
	set {_i} to 1
	if {_b} is "<none>":
		loop {lg::joueurs::*}:
			if {_s} is 29:
				add 1 to {_i}
				set {_s} to 1
			if loop-value's gamemode is not spectator:
				if loop-value is not {_p}:
					add loop-value to {_player.%{_i}%::*}
			add 1 to {_s}
	else:
		loop {lg::joueurs::*}:
			if {_s} is 29:
				add 1 to {_i}
				set {_s} to 1
			if loop-value is not {_b}:
				if loop-value is not {_p}:
					if loop-value's gamemode is not spectator:
						add loop-value to {_player.%{_i}%::*}
			add 1 to {_s}
	if {_b} is "<none>":
		open virtual chest inventory with size 6 with name "&5Choisissez le premier joueur" to {_p}
	else:
		open virtual chest inventory with size 6 with name "&5Choisissez le second joueur" to {_p}
	make a gui slot 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 44, 45, 46, 48, 49, 50, 52 and 53 of {_p} with 1 gray stained glass pane named "&f"
	if {_page} is not 1:
		make a gui slot 47 of {_p} with skull of ("MHF_ArrowLeft" parsed as an offline player) named "Page précédante" to run:
			set {_page2} to {_page} - 1
			lgu_oracle({_p},{_page2},{_b})
	else:
		make a gui slot 47 of {_p} with 1 gray stained glass pane named "&f"
	set {_i2} to {_page} + 1
	if {_player.%{_i2}%::*} is set:
		make a gui slot 51 of {_p} with skull of ("MHF_ArrowRight" parsed as an offline player) named "Page suivante" to run:
			lgu_oracle({_p},{_i2},{_b})
	else:
		make a gui slot 51 of {_p} with 1 gray stained glass pane named "&f"
	set {_s} to 10
	loop {_player.%{_page}%::*}:
		if {_s} is 17:
			set {_s} to 19
		else if {_s} is 26:
			set {_s} to 28
		else if {_s} is 35:
			set {_s} to 37
		else if {_s} is 44:
			set {_s} to 46
		set {_loopvalue} to loop-value
		set {_player1} to {_b}
		make a gui slot {_s} of {_p} with skull of ("%loop-value%" parsed as an offline player) named "&d%loop-value%" to run:
			if {_player1} is "<none>":
				set {_b} to {_loopvalue}
				lgu_oracle({_p},1,"%{_b}%")
			else:
				set {_b2} to {_loopvalue}
				close {_p}'s inventory
				set {lg::power::%{_p}%} to true
				if {lg::%{_player1}%::role} is "Villageois" or "Chasseur" or "Voyante" or "Sorcière" or "Petite fille" or "Ancien" or "Cupidon" or "Ange" or "Renard" or "Enfant sauvage" or "Loup-garou amnésique" or "Voleur" or "Salvateur" or "Inquisiteur" or "Oracle":
					if {lg::%{_b2}%::role} is "Villageois" or "Chasseur" or "Voyante" or "Sorcière" or "Petite fille" or "Ancien" or "Cupidon" or "Ange" or "Renard" or "Enfant sauvage" or "Loup-garou amnésique" or "Voleur" or "Salvateur" or "Inquisiteur" or "Oracle":
						message "&8&l[&5Le joueur &3%{_player1}% &5et &3%{_b2}% &5sont &edans le même camp&5.&8&l]" to {_p}
						stop
					else:
						message "&8&l[&5Le joueur &3%{_player1}% &5et &3%{_b2}% &5sont &edans des camps adverses&5.&8&l]" to {_p}
				else if {lg::%{_player1}%::role} is "Loup-garou" or "Infect père des loups":
					if {lg::%{_b2}%::role} is "Loup-garou" or "Infect père des loups":
						message "&8&l[&5Le joueur &3%{_player1}% &5et &3%{_b2}% &5sont &edans le même camp&5.&8&l]" to {_p}
						stop
					else:
						message "&8&l[&5Le joueur &3%{_player1}% &5et &3%{_b2}% &5sont &edans des camps adverses&5.&8&l]" to {_p}
				else:
					message "&8&l[&5Le joueur &3%{_player1}% &5et &3%{_b2}% &5sont &edans des camps adverses&5.&8&l]" to {_p}



		add 1 to {_s}
function lgu_wildchild(p: player,page: number):
	set {_s} to 1
	set {_i} to 1
	loop {lg::joueurs::*}:
		if loop-value is not {_p}:
			if {_s} is 29:
				add 1 to {_i}
				set {_s} to 1
			if loop-value's gamemode is not spectator:
				add loop-value to {_player.%{_i}%::*}
				add 1 to {_s}
	open virtual chest inventory with size 6 with name "&8Choisir un maître" to {_p}
	make a gui slot 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 44, 45, 46, 48, 49, 50, 52 and 53 of {_p} with 1 gray stained glass pane named "&f"
	if {_page} is not 1:
		make a gui slot 47 of {_p} with skull of ("MHF_ArrowLeft" parsed as an offline player) named "Page précédante" to run:
			set {_page2} to {_page} - 1
			lgu_wildchild({_p},{_page2})
	else:
		make a gui slot 47 of {_p} with 1 gray stained glass pane named "&f"
	set {_i2} to {_page} + 1
	if {_player.%{_i2}%::*} is set:
		make a gui slot 51 of {_p} with skull of ("MHF_ArrowRight" parsed as an offline player) named "Page suivante" to run:
			lgu_wildchild({_p},{_i2})
	else:
		make a gui slot 51 of {_p} with 1 gray stained glass pane named "&f"
	set {_s} to 10
	loop {_player.%{_page}%::*}:
		if {_s} is 17:
			set {_s} to 19
		else if {_s} is 26:
			set {_s} to 28
		else if {_s} is 35:
			set {_s} to 37
		else if {_s} is 44:
			set {_s} to 46
		set {_loopvalue} to loop-value
		make a gui slot {_s} of {_p} with skull of ("%loop-value%" parsed as an offline player) named "&2%loop-value%" to run:
			close {_p}'s inventory
			message "&8&l[&2Tu as choisis le joueur &3%{_loopvalue}% &2comme maître, si il meurt, tu deviendras &cloup-garou&2.&8&l]" to {_p}
			set {lg::%{_loopvalue}%::master} to {_p}
			set {lg::power::%{_p}%} to true
		add 1 to {_s}
function lgu_salvateur(p: player,page: number):
	set {_s} to 1
	set {_i} to 1
	loop {lg::joueurs::*}:
		if {_s} is 29:
			add 1 to {_i}
			set {_s} to 1
		if loop-value's gamemode is not spectator:
			add loop-value to {_player.%{_i}%::*}
			add 1 to {_s}
	open virtual chest inventory with size 6 with name "&8Choisissez un joueur" to {_p}
	make a gui slot 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 44, 45, 46, 48, 49, 50, 52 and 53 of {_p} with 1 gray stained glass pane named "&f"
	if {_page} is not 1:
		make a gui slot 47 of {_p} with skull of ("MHF_ArrowLeft" parsed as an offline player) named "Page précédante" to run:
			set {_page2} to {_page} - 1
			lgu_salvateur({_p},{_page2})
	else:
		make a gui slot 47 of {_p} with 1 gray stained glass pane named "&f"
	set {_i2} to {_page} + 1
	if {_player.%{_i2}%::*} is set:
		make a gui slot 51 of {_p} with skull of ("MHF_ArrowRight" parsed as an offline player) named "Page suivante" to run:
			lgu_salvateur({_p},{_i2})
	else:
		make a gui slot 51 of {_p} with 1 gray stained glass pane named "&f"
	set {_s} to 10
	loop {_player.%{_page}%::*}:
		if {_s} is 17:
			set {_s} to 19
		else if {_s} is 26:
			set {_s} to 28
		else if {_s} is 35:
			set {_s} to 37
		else if {_s} is 44:
			set {_s} to 46
		set {_loopvalue} to loop-value
		make a gui slot {_s} of {_p} with skull of ("%loop-value%" parsed as an offline player) named "&e%loop-value%" to run:
			if {lg::%{_p}%::salvateur} is not {_loopvalue}:
				set {lg::%{_p}%::salvateur} to {_loopvalue}
				close {_p}'s inventory
				message "&8&l[&fTu as béni le joueur &3%{_loopvalue}%&f.&8&l]" to {_p}
				set {_day::*} to {lg::config::day2} split at "-"
				set {_day::1} to {_day::1} parsed as number
				set {_day::2} to {_day::2} parsed as number
				set {_day::1} to {_day::1} * 2
				set {_day::2} to {_day::2} * 2
				set {_day::1} to {_day::1} * 60
				set {_sec} to {_day::1} + {_day::2}
				set {_sec} to "%{_sec}% seconds" parsed as timespan
				apply resistance without any particles to {_loopvalue} for {_sec}
				set {lg::power::%{_p}%} to true
				stop
			close {_p}'s inventory
			message "&cTu as déjà béni ce joueur la dernière fois, change de joueur." to {_p}
		add 1 to {_s}

on break of diamond ore:
	if {lg::info::start} is true:
		if {lg::config::diamondlimit} is true:
			if {lg::%player%::diamondlimit} is not set:
				set {lg::%player%::diamondlimit} to 1
			else:
				if {lg::config::diamondlimitsize} is not equal to {lg::%player%::diamondlimit}:
					add 1 to {lg::%player%::diamondlimit}
				else:
					cancel event
					message "&cVous ne pouvez pas miner plus de %{lg::config::diamondlimitsize}% diamants." to player

on chat:
	if {lg::info::start} is equal to true:
		cancel event
		if {lg::joueurs::%player%} is set:
			if player's gamemode is not spectator:
				if first character of message is not "*" or "!":
					if {lg::config::chat} is equal to "region":
						if {lg::joueurs::%player%} is set:
							loop players in radius 50 of player:
								message "&e%player%: &7%message%" to loop-player
							loop all players:
								if {lg::joueurs::%loop-player%} is not set:
									message "&e%player%: &7%message%" to loop-player
					else if {lg::config::chat} is equal to "open":
						message "&e%player%: &7%message%" to all players
				else if first character of message is "!":
					if player is {lg::amoureux::1} or {lg::amoureux::2}:
						set message to subtext of message from characters 2 to (length of message)
						loop {lg::amoureux::*}:
							message "&8&l[&d%player%&8&l] &d%message%" to loop-value

				else:
					if {lg::current::rev} is true:
						if {lg::%player%::role} is "Loup-garou" or "Loup-garou blanc" or "Infect père des loups":
							if {lg::current::day} is false:
								set message to subtext of message from characters 2 to (length of message)
								loop {lg::joueurs::*}:
									if {lg::%loop-value%::role} is "Loup-garou" or "Loup-garou blanc" or "Infect père des loups":
										message "&8&l[&c%player%&8&l] &c%message%" to loop-value
									else if {lg::%loop-value%::role} is "Petite fille":
										message "&8&l[&cLOUP-GAROU&8&l] &c%message%" to loop-value
							else:
								message "&8&l[&6&lLoup-garou&8&l] &7Vous ne pouvez pas parler aux autres loups-garous le jour." to player
					else:
						message "&8&l[&6&lLoup-garou&8&l] &7Vous ne connaissez pas encore votre rôle." to player
		else:
			loop all players:
				if {lg::joueurs::%loop-player%} is not set:
					message "&8&l[&7%player%&8&l] &7%message%" to loop-player
	else:
		if {lg::%player%::spec} is true:
			cancel event
			if message is not "annuler":
				set {_pseudo} to message parsed as player
				if {lg::spec::%{_pseudo}%} is not set:
					if {_pseudo} is online:
						message "&8&l[&6&lLoup-garou&8&l] &7Vous avez ajouté le joueur &3%{_pseudo}% &7aux spectateurs." to player
						set {lg::spec::%{_pseudo}%} to {_pseudo}
						set {lg::%player%::spec} to false
						lgu_spec(player,1)
					else:
						message "&8&l[&6&lLoup-garou&8&l] &cLe joueur %{_pseudo}% n'est pas connecté." to player
				else:
					message "&8&l[&6&lLoup-garou&8&l] &7Ce joueur est déjà spectateur..." to player
			else:
				delete {lg::%player%::spec}

on damage:
	if {lg::info::start} is true:
		if victim is a player:
			if {lg::joueurs::%victim%} is set:
				if {lg::current::invincible} is not set:
					cancel event
				else:
					if {lg::config::nofire} is true:
						if damage was caused by fire or burning:
							cancel event
							extinguish the victim
					if {lg::config::nodeathbeforepvp} is true:
						if {lg::current::pvp} is not equal to true:
							if (victim's health - final damage) < 1:
								set victim's health to 0.5
								cancel event
					if attacker is a player:
						if {lg::current::pvp} is not equal to true:
							cancel event
						else:
							if {lg::%attacker%::role} is "Loup-garou" or "Infect père des loups" or "Loup-garou blanc":
								if {lg::%victim%::role} is "Loup-garou amnésique":
									wait 25 seconds
									if victim's gamemode is survival:
										if {lg::%victim%::role} is not "Loup-garou":
											set {lg::%victim%::role} to "Loup-garou"
											message "&8&l>> &2&lTu es passé de Loup-garou amnésique à Loup-garou" to victim
											message "&7Tu es un ennemi du village." to victim
											message "&fTu peux parler aux autres loups-garous durant la nuit en mettant un ""*"" devant ton message." to victim
											message "&fTu peux voir la liste des autres loups-garous en faisant /lg lg" to victim
											message "" to victim
											message "&6Tu peux gagner ..." to victim
											message "&8&l>> &fsi les villageois, le loup-garou blanc et l'assassin sont morts." to victim
											message "" to victim
											message "&3Pour faire ceci, tu as le droit à :" to victim
											message "&a&l+ &r&7un effet de force nocturne" to victim
											message "&a&l+ &r&7un effet de vision nocturne" to victim
											loop {lg::joueurs::*}:
												if {lg::%loop-value%::role} is "Loup-garou" or "Infect père des loups" or "Loup-garou blanc":
													message "&8&l[&c&lLG&8&l] &7Le loup-garou amnésique &3%victim% &7est devenu &cloup-garou&7." to loop-value
											set {_osef} to lgu_wincheck()
on death:
	if {lg::info::start} is equal to true:
		if victim is a player:
			if {lg::%victim%::role} is set:
				if {lg::%victim%::role} is "Ancien":
					if {lg::power::%victim%} is not set:
						set {lg::power::%victim%} to true
						set {_stuff::*} to drops
						remove drops from drops
						force victim to respawn
						lgu_tp(victim,true)

						message "&8&l[&aVotre pouvoir vous a ressucité.&8&l]" to victim
						stop
				if {lg::var::%victim%} is not set:
					set {lg::var::%victim%} to location of victim

					loop {lg::joueurs::*}:
						if loop-value is not victim:
							if {lg::current::rev} is true:
								if {lg::%loop-value%::role} is "Sorcière":
									if {lg::power::%loop-value%} is not set:
										message "" to loop-value
										message "<tooltip:&cAttention cette action n'est réalisable qu'une fois.><cmd:/lg power Sorcière %victim%>&8&l[&aCliquez ici dans les 30s pour ressuciter le joueur &3%victim%&8&l]" to loop-value
										message "" to loop-value
										set {_ok} to true

								else if {lg::%loop-value%::role} is "Infect père des loups":
									if {lg::%attacker%::role} is "Loup-garou" or "Loup-garou blanc" or "Infect père des loups":
										if {lg::power::%loop-value%} is not set:
											set {lg::killer::%victim%} to true
											message "" to loop-value
											message "<tooltip:&cAttention cette action n'est réalisable qu'une fois.><cmd:/lg power lg %victim%>&8&l[&aCliquez ici dans les 30s pour transformer le joueur &3%victim% &aen loup-garou&8&l]" to loop-value
											message "" to loop-value
											set {_ok} to true
					if {@debug} is true:
						loop all players:
							if loop-player has permission "lgu.admin.debug" or "lgu.admin.*" or "lgu.*":
								set {_ok} to true
								message "" to loop-player
								message "<cmd:/lg power op %victim%>&8&l[&4ADMIN: &aCliquez ici dans les 30s sauver &3%victim%&8&l]" to loop-player
								message "" to loop-player


					if {_ok} is true:
						if {lg::%victim%::master} is set:
							if {lg::%victim%::master}'s gamemode is survival:
								if {lg::joueurs::%{lg::%victim%::master}%} is set:
									message "&8&l>> &2&lTon maître &3%victim% &2est mort, tu deviens Loup-garou." to {lg::%victim%::master}
									set {lg::%{lg::%victim%::master}%::role} to "Loup-garou"
									message "&7Tu es désormais un ennemi du village." to {lg::%victim%::master}
									message "&fTu peux parler aux autres loups-garous durant la nuit en mettant un ""*"" devant ton message." to {lg::%victim%::master}
									message "&fTu peux voir la liste des autres loups-garous en faisant /lg lg" to {lg::%victim%::master}
									message "" to {lg::%victim%::master}
									message "&6Tu peux gagner ..." to {lg::%victim%::master}
									message "&8&l>> &fsi les villageois, le loup-garou blanc et l'assassin sont morts." to {lg::%victim%::master}
									message "" to {lg::%victim%::master}
									message "&3Pour faire ceci, tu as le droit à :" to {lg::%victim%::master}
									message "&a&l+ &r&7un effet de force nocturne" to {lg::%victim%::master}
									message "&a&l+ &r&7un effet de vision nocturne" to {lg::%victim%::master}
									loop {lg::joueurs::*}:
										if {lg::%loop-value%::role} is "Loup-garou" or "Infect père des loups" or "Loup-garou blanc":
											message "&8&l[&c&lLG&8&l] &7Le joueur &3%{lg::%victim%::master}% &7est devenu &cloup-garou&7." to loop-value
									delete {lg::%victim%::master}
						set {lg::stuff::%victim%::*} to drops
						remove drops from the drops
						clear victim's inventory
						force victim to respawn
						set victim's gamemode to spectator
						apply blindness without any particles to victim for 99999 days
						wait 30 second
						set {_loc} to {lg::var::%victim%}
						if {lg::var::%victim%} is set:
							if {lg::info::start} is equal to true:
								set gamemode of victim to spectator
								teleport victim to {lg::var::%victim%}
								remove blindness from victim
								strike lightning effect at {lg::var::%victim%}
								add {lg::deathitems::items::*} to {lg::stuff::%victim%::*}
								loop {lg::stuff::%victim%::*}:
									drop loop-value at {lg::var::%victim%}
								set {lg::%victim%::ADstuff::*} to {lg::stuff::%victim%::*}
								set {lg::%victim%::ADloc} to {lg::var::%victim%}
								delete {lg::var::%victim%}
								delete {lg::joueurs::%victim%}
								if attacker is a player:
									if {lg::%attacker%::role} is "Voleur":
										message "" to attacker
										if {lg::%victim%::role} is not "Cupidon":
											message "&8&l[&6Lg-UHC&8&l] &f>> &7Tu es devenu %{lg::%victim%::role}%" to attacker
											set {lg::%attacker%::role} to {lg::%victim%::role}
											lgu_rolesgive(attacker,{lg::%victim%::role},false)
											if {lg::%attacker%::role} is "Loup-garou" or "Loup-garou blanc" or "Infect père des loups":
												loop {lg::joueurs::*}:
													if loop-value is not attacker:
														if {lg::%loop-value%::role} is "Loup-garou" or "Loup-garou blanc" or "Infect père des loups":
															message "&8&l[&cLOUP-GAROU&8&l] &c&l%attacker% &r&7 est devenu loup-garou" to loop-value
															if {lg::%attacker%::role} is "Loup-garou blanc":
																set attacker's max health to 12
										else:
											message "<tooltip:&7Cupidon est un dieu, tu ne peux pas voler son rôle.>&8&lCe rôle ne peut pas être volé !" to attacker
										message "" to attacker
								if {lg::amoureux::1} is victim:
									set {_temp1} to {lg::amoureux::1}
									set {_temp2} to {lg::amoureux::2}
									delete {lg::amoureux::*}
									kill {_temp2}
									message "&d%{_temp2}% était amoureux de %{_temp1}%, il meurt donc aussi" to all players

								else if {lg::amoureux::2} is victim:
									set {_temp1} to {lg::amoureux::1}
									set {_temp2} to {lg::amoureux::2}
									delete {lg::amoureux::*}
									kill {_temp1}
									message "&d%{_temp1}% était amoureux de %{_temp2}%, il meurt donc aussi" to all players
								message "" to all players
								if {lg::%victim%::voleur} is not true:
									message "&cLe joueur &e&l%victim% &cest mort, il était &l%{lg::%victim%::role}%" to all players
								else:
									message "&cLe joueur &e&l%victim% &cest mort, il était &lVoleur" to all players
								message "" to all players

								if {lg::%victim%::role} is not "Chasseur":
									delete {lg::%victim%::role}
									wait 1 second
									set {_osef} to lgu_wincheck()
									if {lg::%victim%::role} is "Inquisiteur":
										message "&8&l[&6Lg-UHC&8&l] &f>>Le tueur de %victim% est %{lg::%attacker%::role}%" to all players
								else:
									set {_ok} to lgu_wincheck()
									if {_ok} is not true:
										message "" to victim
										message "<tooltip:&cAttention cette action n'est réalisable qu'une fois.><cmd:/lg power Chasseur>&8&l[&aCliquez ici dans les 30s pour enlever la moitié de la vie d'un joueur.&8&l]" to victim
										message "" to victim
										wait 30 seconds
									delete {lg::%victim%::role}
								set the text of id "LG_UHC_4" to "&3&lJOUEURS: &3%size of {lg::joueurs::*}%"

					else:
						if {lg::%victim%::master} is set:
							if {lg::%victim%::master}'s gamemode is survival:
								if {lg::joueurs::%{lg::%victim%::master}%} is set:
									message "&8&l>> &2&lTon maître &3%victim% &2est mort, tu deviens loup-garou." to {lg::%victim%::master}
									set {lg::%{lg::%victim%::master}%::role} to "Loup-garou"
									message "&7Tu es désormais un ennemi du village." to {lg::%victim%::master}
									message "&fTu peux parler aux autres loups-garous durant la nuit en mettant un ""*"" devant ton message." to {lg::%victim%::master}
									message "&fTu peux voir la liste des autres loups-garous en faisant /lg lg" to {lg::%victim%::master}
									message "" to {lg::%victim%::master}
									message "&6Tu peux gagner ..." to {lg::%victim%::master}
									message "&8&l>> &fsi les villageois, le loup-garou blanc et l'assassin sont morts." to {lg::%victim%::master}
									message "" to {lg::%victim%::master}
									message "&3Pour faire ceci, tu as le droit à :" to {lg::%victim%::master}
									message "&a&l+ &r&7un effet de force nocturne" to {lg::%victim%::master}
									message "&a&l+ &r&7un effet de vision nocturne" to {lg::%victim%::master}
									loop {lg::joueurs::*}:
										if {lg::%loop-value%::role} is "Loup-garou" or "Infect père des loups" or "Loup-garou blanc":
											message "&8&l[&c&lLG&8&l] &7Le joueur &3%{lg::%victim%::master}% &7est devenu &cloup-garou&7." to loop-value
									delete {lg::%victim%::master}
						set {lg::%victim%::ADstuff::*} to drops
						set {_dr::*} to drops
						remove drops from the drops
						force victim to respawn
						add {lg::deathitems::items::*} to {_dr::*}
						set gamemode of victim to spectator
						loop {_dr::*}:
							drop loop-value at {lg::var::%victim%}
						teleport victim to {lg::var::%victim%}
						strike lightning effect at {lg::var::%victim%}
						set {lg::%victim%::ADloc} to {lg::var::%victim%}
						delete {lg::var::%victim%}
						delete {lg::joueurs::%victim%}
						if attacker is a player:
							if {lg::%attacker%::role} is "Voleur":
								message "" to attacker
								if {lg::%victim%::role} is not "Cupidon":
									message "&8&l[&6Lg-UHC&8&l] &f>> &7Tu es devenu %{lg::%victim%::role}%" to attacker
									set {lg::%attacker%::role} to {lg::%victim%::role}
									lgu_rolesgive(attacker,{lg::%victim%::role},false)
									if {lg::%attacker%::role} is "Loup-garou" or "Loup-garou blanc" or "Infect père des loups":
										loop {lg::joueurs::*}:
											if loop-value is not attacker:
												if {lg::%loop-value%::role} is "Loup-garou" or "Loup-garou blanc" or "Infect père des loups":
													message "&8&l[&cLOUP-GAROU&8&l] &c&l%attacker% &r&7 est devenu loup-garou" to loop-value
								else:
									message "<tooltip:&7Cupidon est un dieu, tu ne peux pas voler son rôle.>&8&lCe rôle ne peut pas être volé !" to attacker
								message "" to attacker
						if {lg::amoureux::1} is victim:
							set {_temp1} to {lg::amoureux::1}
							set {_temp2} to {lg::amoureux::2}
							delete {lg::amoureux::*}
							kill {_temp2}
							message "&d%{_temp2}% était amoureux de %{_temp1}%, il meurt donc aussi" to all players
						else if {lg::amoureux::2} is victim:
							set {_temp1} to {lg::amoureux::1}
							set {_temp2} to {lg::amoureux::2}
							delete {lg::amoureux::*}
							kill {_temp1}
							message "&d%{_temp1}% était amoureux de %{_temp2}%, il meurt donc aussi" to all players

						message "" to all players
						if {lg::%victim%::voleur} is not true:
							message "&cLe joueur &e&l%victim% &cest mort, il était &l%{lg::%victim%::role}%" to all players
						else:
							message "&cLe joueur &e&l%victim% &cest mort, il était &lVoleur" to all players
						message "" to all players
						if {lg::%victim%::role} is not "Chasseur":
							if {lg::%victim%::role} is "Inquisiteur":
								message "&8&l[&6Lg-UHC&8&l] &f>>Le tueur de %victim% est %{lg::%attacker%::role}%" to all players
							delete {lg::%victim%::role}
						set the text of id "LG_UHC_4" to "&3&lJOUEURS: &3%size of {lg::joueurs::*}%"
						if {lg::%victim%::role} is "Chasseur":
							set {_ok} to lgu_wincheck()
							if {_ok} is not true:
								message "" to victim
								message "<tooltip:&cAttention cette action n'est réalisable qu'une fois.><cmd:/lg power Chasseur>&8&l[&aCliquez ici dans les 30s pour enlever la moitié de la vie d'un joueur.&8&l]" to victim
								message "" to victim
								wait 30 seconds
								delete {lg::%victim%::role}
						else:
							wait 1 second
							set {_osef} to lgu_wincheck()

on spawn of horse:
	if {lg::info::start} is true:
		if {lg::config::horse} is false:
			cancel event
on quit:
	if {lg::%player%::role} is set:
		if {lg::info::start} is equal to true:
			loop 36 times:
				add slot (loop-number - 1) of player's inventory to {lg::off::%player%::items::*}

			set {lg::off::%player%::helmet} to player's helmet
			set {lg::off::%player%::chestplate} to player's chestplate
			set {lg::off::%player%::leggings} to player's leggings
			set {lg::off::%player%::boots} to player's boots
			set {lg::off::%player%::loc} to location of player
			if {lg::config::deco} is not "friends":
				if {lg::config::deco} is "normal":
					message "&8&l[&6&lLoup-garou&8&l] &7Le joueur &4%player% &7a quitté la partie, il a 30s pour se reconnecter sinon il se fera éliminer de la partie." to all players
					set {_s} to 0
					while {_s} is not 30:
						if player is online:
							message "&8&l[&6&lLoup-garou&8&l] &7Le joueur &3%player% &7s'est reconnecté." to all players
							delete {lg::off::%player%::*}
							stop
						add 1 to {_s}
				set {_list::*} to {lg::off::%player%::items::*}
				add {lg::off::%player%::helmet} to {_list::*}
				add {lg::off::%player%::chestplate} to {_list::*}
				add {lg::off::%player%::leggings} to {_list::*}
				add {lg::off::%player%::boots} to {_list::*}
				add {lg::deathitems::items::*} to {_list::*}
				loop {_list::*}:
					drop loop-value at {lg::off::%player%::loc}
				teleport player to {lg::off::%player%::loc}
				strike lightning effect at {lg::off::%player%::loc}
				delete {lg::joueurs::%player%}
				message "" to all players
				message "&cLe joueur &e&l%player% &cest mort, il était &l%{lg::%player%::role}%" to all players
				message "" to all players
				delete {lg::%player%::role}
				delete {lg::off::%player%::*}
				set {_osef} to lgu_wincheck()
			else:
				message "&8&l[&6&lLoup-garou&8&l] &7Le joueur &4%player% &7a quitté la partie, il peut se reconnecter quand il le souhaite." to all players
on join:
	if {lg::info::start} is equal to true:
		if {lg::joueurs::%player%} is not set:
			clear player's inventory
			set player's gamemode to spectator
			if {lg::spec::%player%} is not set:
				set {lg::spec::%player%} to player
		else:
			if {lg::current::rev} is true:
				message "&8&l[&6&lLoup-garou&8&l] &7Ton rôle: %{lg::%player%::role}%" to player
		try:
			set stylish scoreboard of player to "LG_UHC"

on player portal:
	if {lg::info::start} is equal to true:
		if {lg::config::nether} is false:
			cancel event
on craft fishing rod:
	if {lg::info::start} is equal to true:
		if {lg::config::rod} is false:
			cancel event

#-----------------------------------------------------#
#					Scénarios de Faywyrr 			  #
#				Merci à Faywyrr pour son aide		  #
#-----------------------------------------------------#

on mine of iron ore:
	if {lg::info::start} is true:
		if {lg::config::cutlean} is true:
			cancel the event
			set block to air
			damage player's tool by 1
			wait 2 ticks
			give player 1 iron ingot
			drop 1 xp

on mine of gold ore:
	if {lg::info::start} is true:
		if {lg::config::cutlean} is true:
			cancel the event
			set block to air
			damage player's tool by 1
			wait 2 ticks
			give player 1 gold ingot
			drop 1 xp

on death of a pig:
	if {lg::info::start} is true:
		if {lg::config::cutlean} is true:
			clear drops
			drop 2 cooked porkchop at the pig

on death of a chicken:
	if {lg::info::start} is true:
		if {lg::config::cutlean} is true:
			clear drops
			drop 2 cooked chicken at the chicken
			drop 1 feather at the chicken

on death of a cow:
	if {lg::info::start} is true:
		if {lg::config::cutlean} is true:
			clear drops
			drop 2 steak at the cow
			drop 1 leather at the cow

on death of a sheep:
	if {lg::info::start} is true:
		if {lg::config::cutlean} is true:
			clear drops
			drop 2 cooked mutton at the sheep
on break of log:
	if {lg::info::start} is true:
		if {lg::config::cutlean} is true:
			loop blocks upwards:
				if loop-block is log:
					drop the loop-block-1 at event-block
					set the loop-block to air
					loop blocks in radius 2 around loop-block:
						if loop-block-2 is log:
							drop the loop-block-2 at event-block
							set the loop-block-2 to air
			loop blocks below:
				if loop-block is log:
					drop the loop-block-1 at event-block
					set the loop-block to air
					loop blocks in radius 2 around loop-block:
						if loop-block-2 is log:
							drop the loop-block-2 at event-block
							set the loop-block-2 to air

on break of gravel:
	if {lg::info::start} is true:
		if {lg::config::flint} is true:
			cancel the event
			set the event-block to air
			chance of {lg::config::flintrate}%:
				drop 1 flint at event-block
				stop
			drop 1 gravel at event-block

on leaves decay:
	if {lg::info::start} is true:
		if {lg::config::apple} is true:
			cancel the event
			set the event-block to air
			chance of {lg::config::applerate}%:
				drop 1 apple at event-block

on shoot:
	if {lg::info::start} is true:
		if {lg::config::rod} is false:
			if projectile is a snowball:
				cancel event
